import { useEffect,useState } from 'react'
import { apiDownload, apiRequest } from '../../api/client'
import { formatMoney,formatQuantity } from '../../utils/numbers'
interface Item {id:string;ingredient_code_snapshot:string;ingredient_name_snapshot:string;final_purchase_quantity:string;purchase_unit_snapshot:string;purchase_cost_snapshot:string|null;package_size_snapshot:string;minimum_order_quantity_snapshot:string}
interface Order {id:string;supplier_name_snapshot:string;known_total_cost:string;total_cost:string|null;items:Item[]}
interface Purchase {id:string;purchase_number:string;source_snapshot_id:string;source_snapshot_revision:number;status:'draft'|'confirmed'|'cancelled';known_total_cost:string;total_cost:string|null;created_at:string;created_by_name:string|null;notes:string|null;supplier_summary:{supplier_name:string}[];orders:Order[]}
interface List {items:Purchase[];pagination:{total:number}}
export function PurchasesPage({initialId}:{initialId?:string|null}){
  const [items,setItems]=useState<Purchase[]>([]);const [detail,setDetail]=useState<Purchase|null>(null);const [status,setStatus]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [message,setMessage]=useState('')
  async function load(){try{const query=new URLSearchParams({page:String(page),page_size:'25'});if(status)query.set('purchase_status',status);if(search)query.set('search',search);const data=await apiRequest<List>(`/purchases?${query}`);setItems(data.items);setTotal(data.pagination.total);setError('')}catch{setError('採購列表載入失敗')}}
  async function open(id:string){try{setDetail(await apiRequest<Purchase>(`/purchases/${id}`));setError('')}catch{setError('採購內容載入失敗')}}
  useEffect(()=>{void load()},[page,status,search]);useEffect(()=>{if(initialId)void open(initialId)},[initialId])
  async function transition(action:'confirm'|'cancel'){if(!detail)return;try{const updated=await apiRequest<Purchase>(`/purchases/${detail.id}/${action}`,{method:'POST'});setDetail(updated);setMessage(action==='confirm'?'採購已確認':'採購已作廢');await load()}catch{setError('狀態更新失敗；目前狀態不允許此操作')}}
  return <section><div className="section-heading"><div><h2>正式採購</h2><small>此頁為彙總採購紀錄；日常叫貨請由「食材需求」的每日需求／依供應商資料進行。</small></div></div>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}{detail&&<div className="actions"><button onClick={()=>void apiDownload(`/exports/purchases/${detail.id}/xlsx`).catch(()=>setError('採購 Excel 下載失敗'))}>下載 Excel</button><button onClick={()=>void apiDownload(`/exports/purchases/${detail.id}/pdf`).catch(()=>setError('採購 PDF 下載失敗'))}>下載 PDF</button></div>}
    {!detail?<><div className="toolbar"><label>狀態<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">全部</option><option value="draft">草稿</option><option value="confirmed">已確認</option><option value="cancelled">已作廢</option></select></label><label>編號搜尋<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label></div><table><thead><tr><th>採購編號</th><th>建立日期</th><th>供應商</th><th>狀態</th><th>成本</th><th>建立者</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.purchase_number}</td><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.supplier_summary.map(value=>value.supplier_name).join('、')}</td><td>{item.status}</td><td>{item.total_cost===null?`已知 ${formatMoney(item.known_total_cost)}`:formatMoney(item.total_cost)}</td><td>{item.created_by_name??'—'}</td><td><button onClick={()=>void open(item.id)}>查看</button></td></tr>)}</tbody></table><div className="toolbar"><span>共 {total} 筆</span><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>上一頁</button><button disabled={page*25>=total} onClick={()=>setPage(v=>v+1)}>下一頁</button></div></>:<><button className="secondary" onClick={()=>setDetail(null)}>返回列表</button><h3>{detail.purchase_number}</h3><p>狀態：{detail.status}／來源 Snapshot Revision {detail.source_snapshot_revision}／成本：{detail.total_cost===null?`已知 ${formatMoney(detail.known_total_cost)}`:formatMoney(detail.total_cost)}</p>{detail.orders.map(order=><div key={order.id}><h3>{order.supplier_name_snapshot} — {order.total_cost===null?`已知 ${formatMoney(order.known_total_cost)}`:formatMoney(order.total_cost)}</h3><table><thead><tr><th>食材</th><th>正式採購量</th><th>包裝參考</th><th>最低量參考</th><th>採購成本</th></tr></thead><tbody>{order.items.map(item=><tr key={item.id}><td>{item.ingredient_code_snapshot}　{item.ingredient_name_snapshot}</td><td>{formatQuantity(item.final_purchase_quantity)} {item.purchase_unit_snapshot}</td><td>{formatQuantity(item.package_size_snapshot)}</td><td>{formatQuantity(item.minimum_order_quantity_snapshot)}</td><td>{item.purchase_cost_snapshot===null?'無法估算':formatMoney(item.purchase_cost_snapshot)}</td></tr>)}</tbody></table></div>)}<div className="snapshot-action"><button disabled={detail.status!=='draft'} onClick={()=>void transition('confirm')}>確認採購</button><button className="danger" disabled={detail.status==='cancelled'} onClick={()=>void transition('cancel')}>作廢並保留歷史</button></div></>}
  </section>
}
