import { FormEvent,useCallback,useEffect,useState } from 'react'
import { apiRequest } from '../../api/client'
import { EmptyState,Feedback,LoadingState,PageHeader,StatusBadge,TableFrame } from '../../components/ui/Page'
interface Supplier{id:string;code:string;name:string;phone:string|null;is_active:boolean}interface List{items:Supplier[]}
export function SuppliersPage(){
  const [items,setItems]=useState<Supplier[]>([]),[code,setCode]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setLoading(true);try{setItems((await apiRequest<List>('/suppliers')).items);setError('')}catch{setError('供應商載入失敗，請稍後重試')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])
  async function create(e:FormEvent){e.preventDefault();try{await apiRequest('/suppliers',{method:'POST',body:JSON.stringify({code,name,phone:phone||null})});setCode('');setName('');setPhone('');setMessage('供應商已新增');await load()}catch{setError('供應商新增失敗，請檢查代碼是否重複')}}
  async function edit(x:Supplier){const next=window.prompt('供應商名稱',x.name);if(!next)return;await apiRequest(`/suppliers/${x.id}`,{method:'PATCH',body:JSON.stringify({name:next})});setMessage('供應商已修改');await load()}
  async function toggle(x:Supplier){await apiRequest(`/suppliers/${x.id}/${x.is_active?'deactivate':'reactivate'}`,{method:'POST'});setMessage(x.is_active?'供應商已停用，歷史資料仍保留':'供應商已恢復');await load()}
  async function hardDelete(x:Supplier){if(!window.confirm(`永久刪除「${x.name}」後無法復原；被引用時系統會拒絕。`))return;const password=window.prompt('請重新輸入目前帳號密碼');if(!password)return;try{await apiRequest(`/suppliers/${x.id}/hard-delete`,{method:'POST',body:JSON.stringify({password})});setMessage('未被引用的供應商已永久刪除');await load()}catch{setError('供應商被引用、密碼錯誤或不可永久刪除')}}
  return <section><PageHeader title="供應商管理" description="維護供應商聯絡資訊；停用後不再供新資料選用。"/><form className="panel-form" onSubmit={create}><label>代碼 <span aria-hidden="true">*</span><input value={code} onChange={e=>setCode(e.target.value)} required/></label><label>名稱 <span aria-hidden="true">*</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label>電話<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><button>新增供應商</button></form>{error&&<Feedback type="error">{error}</Feedback>}{message&&<Feedback type="success">{message}</Feedback>}{loading?<LoadingState/>:!items.length?<EmptyState title="尚無供應商" description="請先新增供應商，之後即可指定給食材。"/>:<TableFrame><table><thead><tr><th>代碼</th><th>名稱</th><th>電話</th><th>狀態</th><th>操作</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.phone??'—'}</td><td><StatusBadge active={x.is_active}/></td><td className="actions"><button className="secondary" onClick={()=>void edit(x)}>修改</button><button className="secondary" onClick={()=>void toggle(x)}>{x.is_active?'停用':'恢復'}</button><button className="secondary-danger" onClick={()=>void hardDelete(x)}>永久刪除</button></td></tr>)}</tbody></table></TableFrame>}</section>
}
