import { FormEvent,useCallback,useEffect,useState } from 'react'
import { ApiError,apiRequest } from '../../api/client'
import { EmptyState,Feedback,LoadingState,PageHeader,StatusBadge,TableFrame } from '../../components/ui/Page'

interface Supplier{id:string;code:string;name:string;phone:string|null;is_active:boolean}
interface List{items:Supplier[]}

function supplierError(error:unknown,fallback:string){
  if(error instanceof ApiError&&error.status===409)return error.message.includes('code')?'供應商代碼已存在，請使用其他代碼。':'供應商仍被其他資料引用，無法永久刪除。'
  if(error instanceof ApiError&&error.status===401)return '目前密碼不正確，請重新輸入。'
  return fallback
}

function SupplierEditDialog({supplier,busy,error,onClose,onSave}:{supplier:Supplier;busy:boolean;error:string;onClose:()=>void;onSave:(values:{code:string;name:string;phone:string|null})=>Promise<void>}){
  const [code,setCode]=useState(supplier.code),[name,setName]=useState(supplier.name),[phone,setPhone]=useState(supplier.phone??'')
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[busy,onClose])
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="modal-panel supplier-dialog" role="dialog" aria-modal="true" aria-labelledby="supplier-edit-title"><header><div><h2 id="supplier-edit-title">編輯供應商</h2><p>更新供應商代碼與聯絡資訊。</p></div></header><form onSubmit={event=>{event.preventDefault();void onSave({code:code.trim(),name:name.trim(),phone:phone.trim()||null})}}><div className="supplier-edit-fields"><label>代碼<input autoFocus required maxLength={50} value={code} onChange={event=>setCode(event.target.value)}/></label><label>名稱<input required maxLength={150} value={name} onChange={event=>setName(event.target.value)}/></label><label>電話<input maxLength={50} value={phone} onChange={event=>setPhone(event.target.value)}/></label></div>{error&&<Feedback type="error">{error}</Feedback>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button disabled={busy||!code.trim()||!name.trim()}>{busy?'儲存中…':'儲存'}</button></footer></form></section></div>
}

function SupplierDeleteDialog({supplier,busy,error,onClose,onDelete}:{supplier:Supplier;busy:boolean;error:string;onClose:()=>void;onDelete:(password:string)=>Promise<void>}){
  const [password,setPassword]=useState('')
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[busy,onClose])
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="modal-panel supplier-dialog" role="dialog" aria-modal="true" aria-labelledby="supplier-delete-title"><header><div><h2 id="supplier-delete-title">永久刪除「{supplier.name}」</h2><p>此操作無法復原。若供應商仍被資料引用，系統會拒絕刪除。</p></div></header><form onSubmit={event=>{event.preventDefault();void onDelete(password)}}><label>目前密碼<input autoFocus required type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label>{error&&<Feedback type="error">{error}</Feedback>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button className="danger" disabled={busy||!password}>{busy?'刪除中…':'永久刪除'}</button></footer></form></section></div>
}

export function SuppliersPage(){
  const [items,setItems]=useState<Supplier[]>([]),[code,setCode]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
  const [editing,setEditing]=useState<Supplier|null>(null),[deleting,setDeleting]=useState<Supplier|null>(null),[dialogError,setDialogError]=useState('')
  const load=useCallback(async()=>{setLoading(true);try{setItems((await apiRequest<List>('/suppliers')).items);setError('')}catch{setError('供應商載入失敗，請稍後重試')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])
  async function create(event:FormEvent){event.preventDefault();try{await apiRequest('/suppliers',{method:'POST',body:JSON.stringify({code,name,phone:phone||null})});setCode('');setName('');setPhone('');setMessage('供應商已新增');await load()}catch{setError('供應商新增失敗，請檢查代碼是否重複')}}
  async function saveEdit(values:{code:string;name:string;phone:string|null}){if(!editing)return;setBusy(true);setDialogError('');try{await apiRequest(`/suppliers/${editing.id}`,{method:'PATCH',body:JSON.stringify(values)});setEditing(null);setMessage('供應商已修改');await load()}catch(cause){setDialogError(supplierError(cause,'供應商修改失敗，請稍後重試。'))}finally{setBusy(false)}}
  async function toggle(supplier:Supplier){await apiRequest(`/suppliers/${supplier.id}/${supplier.is_active?'deactivate':'reactivate'}`,{method:'POST'});setMessage(supplier.is_active?'供應商已停用，歷史資料仍保留':'供應商已恢復');await load()}
  async function hardDelete(password:string){if(!deleting)return;setBusy(true);setDialogError('');try{await apiRequest(`/suppliers/${deleting.id}/hard-delete`,{method:'POST',body:JSON.stringify({password})});setDeleting(null);setMessage('未被引用的供應商已永久刪除');await load()}catch(cause){setDialogError(supplierError(cause,'供應商無法永久刪除，請稍後重試。'))}finally{setBusy(false)}}
  return <section><PageHeader title="供應商管理" description="維護供應商聯絡資訊；停用後不再供新資料選用。"/><form className="panel-form" onSubmit={create}><label>代碼 <span aria-hidden="true">*</span><input value={code} onChange={event=>setCode(event.target.value)} required/></label><label>名稱 <span aria-hidden="true">*</span><input value={name} onChange={event=>setName(event.target.value)} required/></label><label>電話<input value={phone} onChange={event=>setPhone(event.target.value)}/></label><button>新增供應商</button></form>{error&&<Feedback type="error">{error}</Feedback>}{message&&<Feedback type="success">{message}</Feedback>}{loading?<LoadingState/>:!items.length?<EmptyState title="尚無供應商" description="請先新增供應商，之後即可指定給食材。"/>:<TableFrame><table><thead><tr><th>代碼</th><th>名稱</th><th>電話</th><th>狀態</th><th>操作</th></tr></thead><tbody>{items.map(supplier=><tr key={supplier.id}><td>{supplier.code}</td><td>{supplier.name}</td><td>{supplier.phone??'—'}</td><td><StatusBadge active={supplier.is_active}/></td><td className="actions"><button className="secondary" onClick={()=>{setDialogError('');setEditing(supplier)}}>修改</button><button className="secondary" onClick={()=>void toggle(supplier)}>{supplier.is_active?'停用':'恢復'}</button><button className="secondary-danger" onClick={()=>{setDialogError('');setDeleting(supplier)}}>永久刪除</button></td></tr>)}</tbody></table></TableFrame>}{editing&&<SupplierEditDialog supplier={editing} busy={busy} error={dialogError} onClose={()=>setEditing(null)} onSave={saveEdit}/>} {deleting&&<SupplierDeleteDialog supplier={deleting} busy={busy} error={dialogError} onClose={()=>setDeleting(null)} onDelete={hardDelete}/>}</section>
}
