import { useEffect,useState } from 'react'
import { apiRequest } from '../../api/client'
interface Header { id:string;source_menus:{menu_name:string}[];created_at:string;created_by_name:string|null;total_estimated_cost:string|null;known_estimated_cost:string;anomaly_summary:{total:number} }
interface Item { id:string;ingredient_code_snapshot:string;ingredient_name_snapshot:string;supplier_name_snapshot:string|null;requirement_quantity:string;requirement_unit:string;suggested_purchase_quantity:string|null;adjusted_quantity:string|null;suggested_purchase_unit_snapshot:string|null;unit_price_snapshot:string|null;estimated_cost_snapshot:string|null;anomaly_snapshot:{code:string;message:string}[] }
interface Detail extends Header { items:Item[];anomaly_snapshot:{code:string;message:string}[] }
interface List { items:Header[];pagination:{page:number;page_size:number;total:number} }

export function SnapshotsPage(){
  const [items,setItems]=useState<Header[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState<string|null>(null)
  async function load(){try{const data=await apiRequest<List>(`/requirement-snapshots?page=${page}&page_size=25`);setItems(data.items);setTotal(data.pagination.total);setError('')}catch{setError('固定快照列表載入失敗')}}
  useEffect(()=>{void load()},[page])
  async function open(id:string){try{setDetail(await apiRequest<Detail>(`/requirement-snapshots/${id}`));setError('')}catch{setError('固定快照內容載入失敗')}}
  async function adjust(item:Item,value:string){if(!detail)return;setSaving(item.id);setMessage('');try{const updated=await apiRequest<Item>(`/requirement-snapshots/${detail.id}/items/${item.id}`,{method:'PATCH',body:JSON.stringify({adjusted_quantity:value})});setDetail({...detail,items:detail.items.map(row=>row.id===item.id?updated:row)});setMessage('人工調整數量已儲存；原始需求與系統建議未變更')}catch{setError('數量儲存失敗，請確認不可為負數')}finally{setSaving(null)}}
  return <section><div className="section-heading"><div><h2>固定需求快照</h2><small>這裡是歷史固定結果；人工調整不會回寫菜單、配方、食材或即時需求。</small></div></div>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}
    {!detail?<><table><thead><tr><th>建立時間</th><th>建立者</th><th>來源菜單</th><th>成本</th><th>異常</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.created_by_name??'—'}</td><td>{item.source_menus.map(menu=>menu.menu_name).join('、')}</td><td>{item.total_estimated_cost??`已知 ${item.known_estimated_cost}`}</td><td>{item.anomaly_summary.total}</td><td><button onClick={()=>void open(item.id)}>查看固定內容</button></td></tr>)}</tbody></table><div className="toolbar"><span>共 {total} 筆</span><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一頁</button><button disabled={page*25>=total} onClick={()=>setPage(value=>value+1)}>下一頁</button></div></>:<><button className="secondary" onClick={()=>setDetail(null)}>返回列表</button><h3>{detail.source_menus.map(menu=>menu.menu_name).join('、')}</h3><p>建立：{new Date(detail.created_at).toLocaleString()}／完整成本：{detail.total_estimated_cost??'無法完整估算'}</p><div className="requirements-table"><table><thead><tr><th>食材</th><th>供應商</th><th>固定需求量</th><th>系統建議</th><th>人工調整量</th><th>價格快照</th><th>成本快照</th><th>異常快照</th></tr></thead><tbody>{detail.items.map(item=><tr key={item.id}><td>{item.ingredient_code_snapshot}　{item.ingredient_name_snapshot}</td><td>{item.supplier_name_snapshot??'未指定'}</td><td>{item.requirement_quantity} {item.requirement_unit}</td><td>{item.suggested_purchase_quantity??'待確認'} {item.suggested_purchase_unit_snapshot}</td><td><div className="inline-form"><input type="number" min="0" step="any" defaultValue={item.adjusted_quantity??''} id={`adjust-${item.id}`}/><button disabled={saving===item.id} onClick={()=>{const input=document.getElementById(`adjust-${item.id}`) as HTMLInputElement;void adjust(item,input.value)}}>儲存</button></div></td><td>{item.unit_price_snapshot??'缺少'}</td><td>{item.estimated_cost_snapshot??'無法估算'}</td><td>{item.anomaly_snapshot.map(a=>a.code).join('、')||'—'}</td></tr>)}</tbody></table></div></>}
  </section>
}
