import { useEffect,useState } from 'react'
import { apiDownload, apiRequest } from '../../api/client'
import { formatMoney,formatQuantity } from '../../utils/numbers'
import { filterSupplierRows,sortDailyRows,supplierOptions,supplierRowsTsv,type DailyRequirementRow } from '../requirements/dailyRequirements'
import { snapshotDailyRows,snapshotPurchaseAction,type SnapshotRequirementItem } from './snapshotRequirements'
import { writeClipboard } from '../../utils/clipboard'

interface Issue {code:string;message:string;item_id?:string}
interface SourceMenu {menu_name:string;start_date:string;end_date:string}
interface Criteria {start_date?:string;end_date?:string;selected_dates?:string[]}
interface Header {id:string;revision:number;criteria:Criteria;source_menus:SourceMenu[];created_at:string;created_by_name:string|null;total_estimated_cost:string|null;known_estimated_cost:string;anomaly_summary:{total:number};locked:boolean;purchase_ready:boolean;blocking_issues:Issue[];purchase_id:string|null;purchase_number:string|null}
interface Item extends SnapshotRequirementItem {requirement_quantity:string;requirement_unit:string;suggested_purchase_quantity:string|null;adjusted_quantity:string|null;suggested_purchase_unit_snapshot:string|null;purchase_unit_snapshot:string|null;configured_purchase_unit_snapshot:string|null;adjusted_estimated_cost:string|null;unit_price_snapshot:string|null;estimated_cost_snapshot:string|null;anomaly_snapshot:{code:string;message:string}[]}
interface Detail extends Header {items:Item[];anomaly_snapshot:{code:string;message:string}[]}
interface List {items:Header[];pagination:{page:number;page_size:number;total:number}}

export function SnapshotsPage({onPurchase}:{onPurchase?:(id:string)=>void}){
  const [items,setItems]=useState<Header[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [view,setView]=useState<'daily'|'supplier'|'total'|'adjust'>('daily');const [supplierKey,setSupplierKey]=useState('');const [copyMessage,setCopyMessage]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState<string|null>(null);const [password,setPassword]=useState('')
  async function load(){try{const data=await apiRequest<List>(`/requirement-snapshots?page=${page}&page_size=25`);setItems(data.items);setTotal(data.pagination.total);setError('')}catch{setError('固定需求紀錄列表載入失敗')}}
  useEffect(()=>{void load()},[page])
  async function open(id:string){try{const data=await apiRequest<Detail>(`/requirement-snapshots/${id}`);setDetail(data);setSupplierKey(supplierOptions(snapshotDailyRows(data.items))[0]?.key??'');setView('daily');setError('')}catch{setError('固定需求內容載入失敗')}}
  async function adjust(item:Item){if(!detail)return;const quantity=(document.getElementById(`adjust-${item.id}`) as HTMLInputElement).value;const unit=(document.getElementById(`unit-${item.id}`) as HTMLInputElement).value;setSaving(item.id);setMessage('');try{await apiRequest<Item>(`/requirement-snapshots/${detail.id}/items/${item.id}`,{method:'PATCH',body:JSON.stringify({adjusted_quantity:quantity,purchase_unit:unit})});await open(detail.id);setMessage('人工調整已儲存；原始需求與系統建議未變更')}catch{setError('調整失敗：紀錄可能已鎖定、數量為負數，或單位不可安全換算')}finally{setSaving(null)}}
  async function createPurchase(){if(!detail)return;setSaving('purchase');try{const purchase=await apiRequest<{id:string;purchase_number:string}>('/purchases',{method:'POST',body:JSON.stringify({snapshot_id:detail.id})});setMessage(`採購 ${purchase.purchase_number} 已建立`);await open(detail.id);onPurchase?.(purchase.id)}catch{setError('建立採購失敗，請先處理所有阻擋問題')}finally{setSaving(null)}}
  async function copySupplier(){if(!detail||!supplierKey)return;try{await writeClipboard(supplierRowsTsv(snapshotDailyRows(detail.items),supplierKey));setCopyMessage('已複製，可直接貼到 Excel')}catch{setCopyMessage('複製失敗，請重新操作')}window.setTimeout(()=>setCopyMessage(''),2500)}
  async function remove(){if(!detail||!password)return;try{await apiRequest(`/requirement-snapshots/${detail.id}/hard-delete`,{method:'POST',body:JSON.stringify({password})});setDetail(null);setPassword('');setMessage('未建立採購的固定需求紀錄已永久刪除');await load()}catch{setError('密碼錯誤、權限不足，或紀錄已有正式採購')}}
  return <section><div className="section-heading"><div><h2>固定需求紀錄／歷史版本</h2><small>保留計算當下的需求、價格、來源與版本；日常叫貨請由「食材需求」的每日需求或依供應商資料進行。</small></div></div>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}
    {!detail?<SnapshotList items={items} page={page} total={total} setPage={setPage} open={open}/>:<><button className="secondary" onClick={()=>setDetail(null)}>返回列表</button><div className="snapshot-history-header"><h3>固定需求紀錄：{detail.source_menus.map(menu=>menu.menu_name).join('、')} — Revision {detail.revision}</h3><p>建立時間：{new Date(detail.created_at).toLocaleString()}／來源菜單：{detail.source_menus.map(menu=>menu.menu_name).join('、')}／計算日期：{criteriaRange(detail)}／完整成本：{detail.total_estimated_cost===null?'無法完整估算':formatMoney(detail.total_estimated_cost)}／{detail.locked?`已鎖定（${detail.purchase_number}）`:detail.purchase_ready?'可建立採購':'尚未符合採購條件'}</p></div>
      <div className="snapshot-main-actions"><button disabled={saving==='export'} onClick={()=>{setSaving('export');void apiDownload(`/exports/requirement-snapshots/${detail.id}/xlsx`).catch(()=>setError('歷史紀錄 Excel 下載失敗')).finally(()=>setSaving(null))}}>下載歷史紀錄 Excel</button>{detail.purchase_id?<button onClick={()=>onPurchase?.(detail.purchase_id!)} disabled={!onPurchase}>{snapshotPurchaseAction(detail.purchase_id)}</button>:<button disabled={!detail.purchase_ready||saving==='purchase'} onClick={()=>void createPurchase()}>{saving==='purchase'?'建立中…':snapshotPurchaseAction(null)}</button>}</div>
      {!detail.purchase_id&&detail.blocking_issues.length>0&&<div className="anomaly-list"><h3>建立正式採購前需處理</h3><ul>{detail.blocking_issues.map((issue,index)=><li className="error" key={`${issue.code}-${index}`}><strong>{issue.code}</strong>：{issue.message}</li>)}</ul></div>}
      <div className="requirement-view-toolbar"><div className="requirement-view-tabs"><button type="button" className={view==='daily'?'':'secondary'} onClick={()=>setView('daily')}>每日需求</button><button type="button" className={view==='supplier'?'':'secondary'} onClick={()=>setView('supplier')}>單一供應商</button><button type="button" className={view==='total'?'':'secondary'} onClick={()=>setView('total')}>總需求</button><button type="button" className={view==='adjust'?'':'secondary'} onClick={()=>setView('adjust')}>進階採購調整</button></div>{view==='supplier'&&<><label className="supplier-selector">供應商<select value={supplierKey} onChange={event=>{setSupplierKey(event.target.value);setCopyMessage('')}}>{supplierOptions(snapshotDailyRows(detail.items)).map(option=><option key={option.key} value={option.key}>{option.label}</option>)}</select></label><button type="button" disabled={!supplierKey} onClick={()=>void copySupplier()}>複製此供應商</button>{copyMessage&&<small className={copyMessage.startsWith('已複製')?'success':'error'}>{copyMessage}</small>}</>}</div>
      {view==='daily'&&<SnapshotDailyTable rows={sortDailyRows(snapshotDailyRows(detail.items),'daily')} showSupplier/>}{view==='supplier'&&<SnapshotDailyTable rows={filterSupplierRows(snapshotDailyRows(detail.items),supplierKey)} showSupplier={false}/>} {view==='total'&&<SnapshotTotalTable items={detail.items}/>} {view==='adjust'&&<div className="legacy-purchase-panel"><p>這些功能保留既有彙總採購流程；人工調整完成後，可使用上方主要按鈕建立正式採購。</p>
        <div className="requirements-table"><table><thead><tr><th>食材</th><th>供應商</th><th>固定需求量</th><th>系統建議</th><th>人工調整量</th><th>採購單位</th><th>調整後成本</th><th>價格快照</th><th>原始成本</th><th></th></tr></thead><tbody>{detail.items.map(item=><tr key={item.id}><td>{item.ingredient_code_snapshot}　{item.ingredient_name_snapshot}</td><td>{item.supplier_name_snapshot??'未指定'}</td><td>{formatQuantity(item.requirement_quantity)} {item.requirement_unit}</td><td>{item.suggested_purchase_quantity===null?'待確認':formatQuantity(item.suggested_purchase_quantity)} {item.suggested_purchase_unit_snapshot}</td><td><input type="number" min="0" step="any" defaultValue={item.adjusted_quantity??''} id={`adjust-${item.id}`} disabled={detail.locked}/></td><td><input defaultValue={item.purchase_unit_snapshot??''} id={`unit-${item.id}`} disabled={detail.locked}/><small>主檔參考：{item.configured_purchase_unit_snapshot??'—'}</small></td><td>{item.adjusted_estimated_cost===null?'無法估算':formatMoney(item.adjusted_estimated_cost)}</td><td>{item.unit_price_snapshot===null?'缺少':formatMoney(item.unit_price_snapshot)}</td><td>{item.estimated_cost_snapshot===null?'無法估算':formatMoney(item.estimated_cost_snapshot)}</td><td><button disabled={detail.locked||saving===item.id} onClick={()=>void adjust(item)}>儲存調整</button></td></tr>)}</tbody></table></div>
      </div>}
      {!detail.locked&&<div className="snapshot-delete"><label>永久刪除密碼<input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password"/></label><button className="danger" disabled={!password} onClick={()=>void remove()}>永久刪除未建採購紀錄</button></div>}</>}
  </section>
}

function SnapshotList({items,page,total,setPage,open}:{items:Header[];page:number;total:number;setPage:React.Dispatch<React.SetStateAction<number>>;open:(id:string)=>Promise<void>}){return <><table><thead><tr><th>建立時間</th><th>Revision</th><th>建立者</th><th>來源菜單</th><th>成本</th><th>異常</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.revision}</td><td>{item.created_by_name??'—'}</td><td>{item.source_menus.map(menu=>menu.menu_name).join('、')}</td><td>{item.total_estimated_cost===null?`已知 ${formatMoney(item.known_estimated_cost)}`:formatMoney(item.total_estimated_cost)}</td><td>{item.anomaly_summary.total}</td><td><button onClick={()=>void open(item.id)}>查看固定內容</button></td></tr>)}</tbody></table><div className="toolbar"><span>共 {total} 筆</span><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一頁</button><button disabled={page*25>=total} onClick={()=>setPage(value=>value+1)}>下一頁</button></div></>}

function SnapshotDailyTable({rows,showSupplier}:{rows:DailyRequirementRow[];showSupplier:boolean}){if(!rows.length)return <p>這份固定需求沒有符合條件的每日來源明細。</p>;return <div className="requirements-table"><table><thead><tr><th>使用日期</th><th>菜單</th>{showSupplier&&<th>供應商</th>}<th>食材編號</th><th>食材</th><th>需求量</th><th>單位</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.requirement_date}-${row.menu_id}-${row.supplier_id??'none'}-${row.ingredient_id}-${row.unit}`}><td>{row.requirement_date}</td><td>{row.menu_name}</td>{showSupplier&&<td>{row.supplier_name??'未指定供應商'}</td>}<td>{row.ingredient_code}</td><td>{row.ingredient_name}</td><td>{formatQuantity(row.quantity)}</td><td>{row.unit}</td></tr>)}</tbody></table></div>}
function SnapshotTotalTable({items}:{items:Item[]}){return <div className="requirements-table"><table><thead><tr><th>食材編號</th><th>食材</th><th>供應商</th><th>固定需求量</th><th>單位</th><th>原始成本</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.ingredient_code_snapshot}</td><td>{item.ingredient_name_snapshot}</td><td>{item.supplier_name_snapshot??'未指定供應商'}</td><td>{formatQuantity(item.requirement_quantity)}</td><td>{item.requirement_unit}</td><td>{item.estimated_cost_snapshot===null?'無法估算':formatMoney(item.estimated_cost_snapshot)}</td></tr>)}</tbody></table></div>}
function criteriaRange(detail:Detail){if(detail.criteria.selected_dates?.length){const dates=[...detail.criteria.selected_dates].sort();return `${dates[0]}～${dates.at(-1)}`}if(detail.criteria.start_date&&detail.criteria.end_date)return `${detail.criteria.start_date}～${detail.criteria.end_date}`;const starts=detail.source_menus.map(menu=>menu.start_date).filter(Boolean).sort();const ends=detail.source_menus.map(menu=>menu.end_date).filter(Boolean).sort();return starts.length&&ends.length?`${starts[0]}～${ends.at(-1)}`:'全部來源日期'}
