import { useEffect,useState } from 'react'
import { apiDownload, apiRequest } from '../../api/client'
interface Issue {code:string;message:string;item_id?:string}
interface Header {id:string;revision:number;source_menus:{menu_name:string}[];created_at:string;created_by_name:string|null;total_estimated_cost:string|null;known_estimated_cost:string;anomaly_summary:{total:number};locked:boolean;purchase_ready:boolean;blocking_issues:Issue[];purchase_id:string|null;purchase_number:string|null}
interface Item {id:string;ingredient_code_snapshot:string;ingredient_name_snapshot:string;supplier_name_snapshot:string|null;requirement_quantity:string;requirement_unit:string;suggested_purchase_quantity:string|null;adjusted_quantity:string|null;suggested_purchase_unit_snapshot:string|null;purchase_unit_snapshot:string|null;configured_purchase_unit_snapshot:string|null;adjusted_estimated_cost:string|null;unit_price_snapshot:string|null;estimated_cost_snapshot:string|null;anomaly_snapshot:{code:string;message:string}[]}
interface Detail extends Header {items:Item[];anomaly_snapshot:{code:string;message:string}[]}
interface List {items:Header[];pagination:{page:number;page_size:number;total:number}}

export function SnapshotsPage({onPurchase}:{onPurchase?:(id:string)=>void}){
  const [items,setItems]=useState<Header[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [error,setError]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState<string|null>(null);const [password,setPassword]=useState('')
  async function load(){try{const data=await apiRequest<List>(`/requirement-snapshots?page=${page}&page_size=25`);setItems(data.items);setTotal(data.pagination.total);setError('')}catch{setError('固定快照列表載入失敗')}}
  useEffect(()=>{void load()},[page])
  async function open(id:string){try{setDetail(await apiRequest<Detail>(`/requirement-snapshots/${id}`));setError('')}catch{setError('固定快照內容載入失敗')}}
  async function adjust(item:Item){if(!detail)return;const quantity=(document.getElementById(`adjust-${item.id}`) as HTMLInputElement).value;const unit=(document.getElementById(`unit-${item.id}`) as HTMLInputElement).value;setSaving(item.id);setMessage('');try{await apiRequest<Item>(`/requirement-snapshots/${detail.id}/items/${item.id}`,{method:'PATCH',body:JSON.stringify({adjusted_quantity:quantity,purchase_unit:unit})});await open(detail.id);setMessage('人工調整已儲存；原始需求與系統建議未變更')}catch{setError('調整失敗：快照可能已鎖定、數量為負數，或單位不可安全換算')}finally{setSaving(null)}}
  async function createPurchase(){if(!detail)return;setSaving('purchase');try{const purchase=await apiRequest<{id:string;purchase_number:string}>('/purchases',{method:'POST',body:JSON.stringify({snapshot_id:detail.id})});setMessage(`採購 ${purchase.purchase_number} 已建立`);await open(detail.id);onPurchase?.(purchase.id)}catch{setError('建立採購失敗，請先處理所有阻擋問題')}finally{setSaving(null)}}
  async function remove(){if(!detail||!password)return;try{await apiRequest(`/requirement-snapshots/${detail.id}/hard-delete`,{method:'POST',body:JSON.stringify({password})});setDetail(null);setPassword('');setMessage('未建立採購的快照已永久刪除');await load()}catch{setError('密碼錯誤、權限不足，或快照已有正式採購')}}
  return <section><div className="section-heading"><div><h2>固定需求快照</h2><small>這裡是歷史固定結果；人工調整不會回寫菜單、配方、食材或即時需求。</small></div></div>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}
    {!detail?<><table><thead><tr><th>建立時間</th><th>Revision</th><th>建立者</th><th>來源菜單</th><th>成本</th><th>異常</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.revision}</td><td>{item.created_by_name??'—'}</td><td>{item.source_menus.map(menu=>menu.menu_name).join('、')}</td><td>{item.total_estimated_cost??`已知 ${item.known_estimated_cost}`}</td><td>{item.anomaly_summary.total}</td><td><button onClick={()=>void open(item.id)}>查看固定內容</button></td></tr>)}</tbody></table><div className="toolbar"><span>共 {total} 筆</span><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一頁</button><button disabled={page*25>=total} onClick={()=>setPage(value=>value+1)}>下一頁</button></div></>:<><button className="secondary" onClick={()=>setDetail(null)}>返回列表</button><h3>{detail.source_menus.map(menu=>menu.menu_name).join('、')} — Revision {detail.revision}</h3><p>建立：{new Date(detail.created_at).toLocaleString()}／完整成本：{detail.total_estimated_cost??'無法完整估算'}／{detail.locked?`已鎖定（${detail.purchase_number}）`:detail.purchase_ready?'可建立採購':'尚未符合採購條件'}</p>
      {detail.blocking_issues.length>0&&<div className="anomaly-list"><h3>採購阻擋問題</h3><ul>{detail.blocking_issues.map((issue,index)=><li className="error" key={`${issue.code}-${index}`}><strong>{issue.code}</strong>：{issue.message}</li>)}</ul></div>}
      <div className="requirements-table"><table><thead><tr><th>食材</th><th>供應商</th><th>固定需求量</th><th>系統建議</th><th>人工調整量</th><th>採購單位</th><th>調整後成本</th><th>價格快照</th><th>原始成本</th><th></th></tr></thead><tbody>{detail.items.map(item=><tr key={item.id}><td>{item.ingredient_code_snapshot}　{item.ingredient_name_snapshot}</td><td>{item.supplier_name_snapshot??'未指定'}</td><td>{item.requirement_quantity} {item.requirement_unit}</td><td>{item.suggested_purchase_quantity??'待確認'} {item.suggested_purchase_unit_snapshot}</td><td><input type="number" min="0" step="any" defaultValue={item.adjusted_quantity??''} id={`adjust-${item.id}`} disabled={detail.locked}/></td><td><input defaultValue={item.purchase_unit_snapshot??''} id={`unit-${item.id}`} disabled={detail.locked}/><small>主檔參考：{item.configured_purchase_unit_snapshot??'—'}</small></td><td>{item.adjusted_estimated_cost??'無法估算'}</td><td>{item.unit_price_snapshot??'缺少'}</td><td>{item.estimated_cost_snapshot??'無法估算'}</td><td><button disabled={detail.locked||saving===item.id} onClick={()=>void adjust(item)}>儲存調整</button></td></tr>)}</tbody></table></div>
      <div className="snapshot-action"><button disabled={saving==='export'} onClick={()=>{setSaving('export');void apiDownload(`/exports/requirement-snapshots/${detail.id}/xlsx`).catch(()=>setError('快照 Excel 下載失敗')).finally(()=>setSaving(null))}}>下載 Excel</button><button disabled={detail.locked||!detail.purchase_ready||saving==='purchase'} onClick={()=>void createPurchase()}>{saving==='purchase'?'建立中…':'建立正式採購'}</button>{detail.purchase_id&&onPurchase&&<button className="secondary" onClick={()=>onPurchase(detail.purchase_id!)}>查看採購</button>}</div>
      {!detail.locked&&<div className="snapshot-delete"><label>永久刪除密碼<input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password"/></label><button className="danger" disabled={!password} onClick={()=>void remove()}>永久刪除未建採購快照</button></div>}</>}
  </section>
}
