import { useCallback, useEffect, useState } from 'react'
import { apiRequest } from '../../api/client'
import { EmptyState, Feedback, LoadingState, PageHeader, TableFrame } from '../../components/ui/Page'
import { PaginationControls } from '../../components/ui/PaginationControls'
import { useDebouncedValue } from '../../utils/useDebouncedValue'

type Summary={id:string;actor_display_name:string;actor_username:string;action:string;entity_type:string;entity_label:string|null;created_at:string}
type Detail=Summary&{before_data:Record<string,unknown>|null;after_data:Record<string,unknown>|null;metadata:Record<string,unknown>;request_id:string|null;ip_address:string|null}
type List={items:Summary[];pagination:{total:number}}
const actions:Record<string,string>={user_created:'新增使用者',user_updated:'修改使用者',user_role_changed:'變更角色',user_deactivated:'停用使用者',user_reactivated:'恢復使用者',password_reset:'重設密碼',password_changed:'修改自己的密碼',category_create:'新增分類',category_update:'修改分類',category_reorder:'調整分類順序',category_deactivate:'停用分類',category_reactivate:'恢復分類',category_hard_delete:'永久刪除分類',supplier_create:'新增供應商',supplier_update:'修改供應商',supplier_reorder:'調整供應商順序',supplier_deactivate:'停用供應商',supplier_reactivate:'恢復供應商',supplier_hard_delete:'永久刪除供應商',ingredient_create:'新增食材',ingredient_update:'修改食材',ingredient_price_change:'修改價格',ingredient_deactivate:'停用食材',ingredient_reactivate:'恢復食材',ingredient_hard_delete:'永久刪除食材',ingredient_nutrition_mapping_change:'變更食材營養對應',nutrition_import_confirm:'匯入官方營養資料',nutrition_manual_create:'新增手動營養食品',nutrition_manual_update:'修改手動營養食品',nutrition_manual_deactivate:'停用手動營養食品',nutrition_manual_reactivate:'恢復手動營養食品',nutrition_hard_delete:'永久刪除手動營養食品',dish_create:'新增菜色',dish_update:'修改菜色',dish_deactivate:'停用菜色',dish_reactivate:'恢復菜色',dish_hard_delete:'永久刪除菜色',recipe_replace:'更新標準配方',menu_create:'新增菜單',menu_update:'修改菜單',menu_deactivate:'停用菜單',menu_reactivate:'恢復菜單',menu_hard_delete:'永久刪除菜單',meal_type_create:'新增餐別',meal_type_update:'修改餐別',meal_type_reorder:'調整餐別順序',meal_type_deactivate:'停用餐別',meal_type_reactivate:'恢復餐別',meal_type_hard_delete:'永久刪除餐別',menu_editor_save:'儲存菜單內容',copy_day:'複製單日菜單',copy_week:'複製整週菜單',snapshot_create:'建立固定需求',snapshot_item_adjust:'調整固定需求',snapshot_hard_delete:'永久刪除固定需求',purchase_create:'建立正式採購',purchase_confirm:'確認採購',purchase_cancel:'作廢採購'}
const entities:Record<string,string>={user:'使用者',ingredient_category:'食材分類',dish_category:'菜色分類',menu_category:'菜單分類',supplier:'供應商',ingredient:'食材',dish:'菜色',recipe:'標準配方',menu:'菜單',menu_meal_type:'餐別',requirement_snapshot:'固定需求',requirement_snapshot_item:'需求項目',purchase:'正式採購'}
const fieldLabels:Record<string,string>={username:'帳號',display_name:'顯示名稱',role:'角色',is_active:'狀態',name:'名稱',code:'代碼',current_price:'目前價格',status:'狀態',adjusted_quantity:'調整數量',purchase_unit_snapshot:'採購單位'}
function valueText(value:unknown){if(value===null||value===undefined)return '—';if(typeof value==='boolean')return value?'是':'否';if(typeof value==='object')return Array.isArray(value)?`${value.length} 筆資料`:'已記錄詳細內容';return String(value)}
function Diff({title,data}:{title:string;data:Record<string,unknown>|null}){return <section className="audit-diff"><h3>{title}</h3>{!data?<p>無</p>:<dl>{Object.entries(data).map(([key,value])=><div key={key}><dt>{fieldLabels[key]??key}</dt><dd>{valueText(value)}</dd></div>)}</dl>}</section>}

export function AuditLogsPage(){
  const [items,setItems]=useState<Summary[]>([]),[detail,setDetail]=useState<Detail|null>(null),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[total,setTotal]=useState(0)
  const [keyword,setKeyword]=useState(''),debouncedKeyword=useDebouncedValue(keyword),[action,setAction]=useState(''),[entityType,setEntityType]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const invalidDates=dateFrom&&dateTo&&dateFrom>dateTo?'開始日期不可晚於結束日期。':''
  const load=useCallback(async()=>{if(invalidDates)return;setLoading(true);try{const query=new URLSearchParams({page:String(page),page_size:String(pageSize)});if(debouncedKeyword)query.set('keyword',debouncedKeyword);if(action)query.set('action',action);if(entityType)query.set('entity_type',entityType);if(dateFrom)query.set('date_from',dateFrom);if(dateTo)query.set('date_to',dateTo);const result=await apiRequest<List>(`/audit-logs?${query}`);setItems(result.items);setTotal(result.pagination.total);setError('')}catch{setError('操作紀錄載入失敗，請稍後再試。')}finally{setLoading(false)}},[action,dateFrom,dateTo,debouncedKeyword,entityType,invalidDates,page,pageSize])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!detail)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setDetail(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[detail])
  async function open(id:string){try{setDetail(await apiRequest<Detail>(`/audit-logs/${id}`))}catch{setError('操作紀錄內容載入失敗。')}}
  return <section><PageHeader title="操作紀錄" description="查詢重要資料由誰、在何時進行了什麼變更。"/><div className="toolbar"><label>關鍵字<input value={keyword} onChange={event=>{setKeyword(event.target.value);setPage(1)}} placeholder="操作者或資料名稱"/></label><label>動作<select value={action} onChange={event=>{setAction(event.target.value);setPage(1)}}><option value="">全部</option>{Object.entries(actions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>資料類型<select value={entityType} onChange={event=>{setEntityType(event.target.value);setPage(1)}}><option value="">全部</option>{Object.entries(entities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>開始日期<input type="date" value={dateFrom} onChange={event=>{setDateFrom(event.target.value);setPage(1)}}/></label><label>結束日期<input type="date" value={dateTo} onChange={event=>{setDateTo(event.target.value);setPage(1)}}/></label></div>{invalidDates&&<Feedback type="error">{invalidDates}</Feedback>}{error&&<Feedback type="error">{error}</Feedback>}
    {loading?<LoadingState/>:!items.length?<EmptyState title="沒有符合條件的操作紀錄"/>:<TableFrame><table><thead><tr><th>時間</th><th>操作者</th><th>動作</th><th>資料類型</th><th>資料</th><th>摘要</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.actor_display_name}<small>{item.actor_username}</small></td><td>{actions[item.action]??item.action}</td><td>{entities[item.entity_type]??item.entity_type}</td><td>{item.entity_label??'—'}</td><td>{item.action.includes('update')||item.action.includes('replace')||item.action.includes('adjust')?'已記錄修改前後內容':'操作已完成'}</td><td><button className="secondary" onClick={()=>void open(item.id)}>查看</button></td></tr>)}</tbody></table></TableFrame>}<PaginationControls page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/>
    {detail&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setDetail(null)}}><section className="modal-panel audit-dialog" role="dialog" aria-modal="true"><header><div><h2>{actions[detail.action]??detail.action}</h2><p>{detail.actor_display_name}｜{new Date(detail.created_at).toLocaleString()}｜{detail.entity_label??entities[detail.entity_type]??detail.entity_type}</p></div></header><div className="audit-diff-grid"><Diff title="修改前" data={detail.before_data}/><Diff title="修改後" data={detail.after_data}/></div><footer><button className="secondary" onClick={()=>setDetail(null)}>關閉</button></footer></section></div>}</section>
}
