import {useEffect,useMemo,useRef,useState} from 'react'
import {ApiError,apiBlobUrl,apiRequest} from '../../api/client'
import {EmptyState,Feedback,LoadingState,TableFrame} from '../../components/ui/Page'
import type {Dish} from '../dishes/DishesPage'
import {aggregateBatches,durationFromInput,durationToInput,DurationUnit,formatDuration,formatProductionNumber} from './presentation'
import {resolveProfileLoad} from './profileLoading'

const uses={main_ingredient:'主食材',preprocessing:'前處理',marinade:'醃料',seasoning:'烹調調味',sauce:'醬汁',final_addition:'最後加入',garnish:'裝飾'} as const
const steps={wash:'清洗',cut:'切',chop:'剁',marinate:'醃製',blanch:'汆燙',thaw:'退冰',stir_fry:'拌炒',boil:'水煮',braise:'燉煮／滷',steam:'蒸',bake:'烘烤',fry:'油炸',pan_fry:'煎',add_ingredient:'加入食材',add_water:'加水',stir:'攪拌',flip:'翻面',thicken:'勾芡',sauce:'淋醬／拌料',garnish:'撒料／裝飾',final_addition:'最後加入',portion:'分裝',plating:'擺盤',quality_check:'成品確認',other:'其他'} as const
type Usage=keyof typeof uses
type StepType=keyof typeof steps
type Tab='basic'|'versions'|'ingredients'|'steps'|'preview'
interface Ingredient{id:string;ingredient_name:string;ingredient_code:string;quantity:string;unit:string;usage_category:Usage;quantity_note:string|null;notes:string|null}
interface Step{id:string;step_order:number;step_type:StepType;title:string|null;instruction:string|null;equipment:string|null;duration_seconds:number|null;temperature_celsius:string|null;batch_size:number|null;servings_per_tray:number|null;trays_per_batch:number|null;quantity_note:string|null;notes:string|null}
interface Version{id:string;serving_count:number;name:string|null;is_official:boolean;notes:string|null;ingredients:Ingredient[];steps:Step[]}
interface Profile{id:string;dish_id:string;dish_name:string;max_batch_size:number;notes:string|null;has_image:boolean;updated_at:string;versions:Version[]}
interface Plan{diner_count:number;batch_count:number;batches:{batch_number:number;serving_count:number;official:boolean}[]}

const tabLabels:Record<Tab,string>={basic:'基本設定',versions:'常用製作份數',ingredients:'食材用量',steps:'製作步驟',preview:'製作計畫預覽'}
const heatedSteps=new Set<StepType>(['blanch','stir_fry','boil','braise','steam','bake','fry','pan_fry'])
const temperatureSteps=new Set<StepType>(['steam','bake','fry','pan_fry'])
const traySteps=new Set<StepType>(['steam','bake'])
const timedSteps=new Set<StepType>(['marinate',...heatedSteps])

function friendlyError(cause:unknown,fallback:string){return cause instanceof ApiError&&cause.status<500?cause.message:fallback}

function Progress({current}:{current:number}){
  return <ol className="production-wizard-progress" aria-label={`建立進度，第 ${current} 步，共 4 步`}>{['設定每批人數','選擇常用份數','確認食材用量','建立製作步驟'].map((label,index)=><li key={label} className={index+1===current?'active':index+1<current?'complete':''}><span>{index+1}</span>{label}</li>)}</ol>
}

function IngredientEditor({dishId,versionId,item,isAdmin,onSaved}:{dishId:string;versionId:string;item:Ingredient;isAdmin:boolean;onSaved:(value:Profile)=>void}){
  const [editing,setEditing]=useState(false),[value,setValue]=useState(item),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>setValue(item),[item])
  async function save(){setBusy(true);setError('');try{onSaved(await apiRequest<Profile>(`/dishes/${dishId}/production-profile/versions/${versionId}/ingredients/${item.id}`,{method:'PATCH',body:JSON.stringify({quantity:value.quantity,usage_category:value.usage_category,quantity_note:value.quantity_note||null})}));setEditing(false)}catch(cause){setError(friendlyError(cause,'食材用量儲存失敗'))}finally{setBusy(false)}}
  return <tr><td><strong>{item.ingredient_code}｜{item.ingredient_name}</strong></td><td>{editing?<input aria-label={`${item.ingredient_name}用量`} type="number" min="0" step="any" value={value.quantity} onChange={event=>setValue({...value,quantity:event.target.value})}/>:formatProductionNumber(item.quantity)}</td><td>{item.unit}</td><td>{editing?<select value={value.usage_category} onChange={event=>setValue({...value,usage_category:event.target.value as Usage})}>{Object.entries(uses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>:uses[item.usage_category]}</td><td>{editing?<input value={value.quantity_note??''} onChange={event=>setValue({...value,quantity_note:event.target.value})}/>:item.quantity_note||'—'}</td><td>{error&&<small className="error">{error}</small>}{isAdmin&&(editing?<span className="actions"><button disabled={busy} onClick={()=>void save()}>{busy?'儲存中…':'儲存'}</button><button className="secondary" disabled={busy} onClick={()=>{setValue(item);setEditing(false)}}>取消</button></span>:<button className="secondary" onClick={()=>setEditing(true)}>修改</button>)}</td></tr>
}

function StepFields({value,onChange}:{value:Step;onChange:(value:Step)=>void}){
  const [advanced,setAdvanced]=useState(false),initial=durationToInput(value.duration_seconds),[duration,setDuration]=useState(initial.value),[durationUnit,setDurationUnit]=useState<DurationUnit>(initial.unit)
  useEffect(()=>{const next=durationToInput(value.duration_seconds);setDuration(next.value);setDurationUnit(next.unit)},[value.id])
  const updateDuration=(nextValue:string,nextUnit:DurationUnit)=>{setDuration(nextValue);setDurationUnit(nextUnit);onChange({...value,duration_seconds:durationFromInput(nextValue,nextUnit)})}
  const capacity=value.servings_per_tray&&value.trays_per_batch?value.servings_per_tray*value.trays_per_batch:null
  return <div className="production-step-editor-fields"><label>這一步要做什麼<textarea value={value.instruction??''} onChange={event=>onChange({...value,instruction:event.target.value})} placeholder="例如：加入醃料抓拌均勻，靜置入味。"/></label>{timedSteps.has(value.step_type)&&<label>需要多久<div className="duration-input"><input type="number" min="0" step="any" value={duration} onChange={event=>updateDuration(event.target.value,durationUnit)}/><select aria-label="時間單位" value={durationUnit} onChange={event=>updateDuration(duration,event.target.value as DurationUnit)}><option value="seconds">秒</option><option value="minutes">分鐘</option><option value="hours">小時</option></select></div></label>}{heatedSteps.has(value.step_type)&&<label>使用設備<input value={value.equipment??''} onChange={event=>onChange({...value,equipment:event.target.value})} placeholder="例如：蒸箱、油炸鍋"/></label>}{temperatureSteps.has(value.step_type)&&<label>溫度（°C）<input type="number" min="-100" max="500" value={value.temperature_celsius??''} onChange={event=>onChange({...value,temperature_celsius:event.target.value||null})}/></label>}{heatedSteps.has(value.step_type)&&<label>一次處理人數<input type="number" min="1" value={value.batch_size??''} onChange={event=>onChange({...value,batch_size:event.target.value?Number(event.target.value):null})}/><small>這個步驟一次可以處理幾人份。</small></label>}{traySteps.has(value.step_type)&&<><label>每盤可裝幾人份<input type="number" min="1" value={value.servings_per_tray??''} onChange={event=>onChange({...value,servings_per_tray:event.target.value?Number(event.target.value):null})}/></label><label>一次可放幾盤<input type="number" min="1" value={value.trays_per_batch??''} onChange={event=>onChange({...value,trays_per_batch:event.target.value?Number(event.target.value):null})}/></label></>}{capacity&&<p className="capacity-hint">依目前設定，一次可處理約 <strong>{capacity} 人份</strong>。</p>}<button type="button" className="text-button" onClick={()=>setAdvanced(current=>!current)}>{advanced?'收起其他設定':'顯示其他設定'}</button>{advanced&&<div className="production-advanced-fields"><label>步驟名稱<input value={value.title??''} onChange={event=>onChange({...value,title:event.target.value})}/></label><label>用量提醒<input value={value.quantity_note??''} onChange={event=>onChange({...value,quantity_note:event.target.value})}/></label><label>其他提醒<input value={value.notes??''} onChange={event=>onChange({...value,notes:event.target.value})}/></label></div>}</div>
}

function StepCard({dishId,versionId,item,index,count,isAdmin,onSaved,onMove}:{dishId:string;versionId:string;item:Step;index:number;count:number;isAdmin:boolean;onSaved:(value:Profile)=>void;onMove:(direction:-1|1)=>void}){
  const [expanded,setExpanded]=useState(false),[value,setValue]=useState(item),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>setValue(item),[item])
  const summary=[item.equipment,formatDuration(item.duration_seconds),item.temperature_celsius?`${formatProductionNumber(item.temperature_celsius)}°C`:null,item.batch_size?`一次 ${item.batch_size} 人份`:null].filter(Boolean).join('・')
  async function save(){setBusy(true);setError('');try{onSaved(await apiRequest<Profile>(`/dishes/${dishId}/production-profile/versions/${versionId}/steps/${item.id}`,{method:'PATCH',body:JSON.stringify(value)}));setExpanded(false)}catch(cause){setError(friendlyError(cause,'製作步驟儲存失敗'))}finally{setBusy(false)}}
  async function remove(){if(!window.confirm('確定刪除這個製作步驟？'))return;setBusy(true);try{onSaved(await apiRequest<Profile>(`/dishes/${dishId}/production-profile/versions/${versionId}/steps/${item.id}`,{method:'DELETE'}))}catch(cause){setError(friendlyError(cause,'製作步驟刪除失敗'))}finally{setBusy(false)}}
  return <article className={`production-step-card ${expanded?'expanded':''}`}><header><span className="step-number">{item.step_order}</span><div><strong>{item.title||steps[item.step_type]}</strong><p>{item.instruction||'尚未填寫操作內容'}</p>{summary&&<small>{summary}</small>}</div><button className="secondary" onClick={()=>setExpanded(current=>!current)}>{expanded?'收起':'查看／修改'}</button></header>{expanded&&<div className="production-step-card-body"><label>步驟類型<select disabled={!isAdmin} value={value.step_type} onChange={event=>setValue({...value,step_type:event.target.value as StepType})}>{Object.entries(steps).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><StepFields value={value} onChange={setValue}/>{error&&<Feedback type="error">{error}</Feedback>}{isAdmin&&<footer><span className="actions"><button className="secondary" disabled={index===0||busy} onClick={()=>onMove(-1)}>上移</button><button className="secondary" disabled={index===count-1||busy} onClick={()=>onMove(1)}>下移</button></span><span className="actions"><button className="danger" disabled={busy} onClick={()=>void remove()}>刪除</button><button disabled={busy} onClick={()=>void save()}>{busy?'儲存中…':'儲存步驟'}</button></span></footer>}</div>}</article>
}

function NewStep({dishId,version,onSaved,onCancel}:{dishId:string;version:Version;onSaved:(value:Profile)=>void;onCancel:()=>void}){
  const [type,setType]=useState<StepType|null>(null),[value,setValue]=useState<Step|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  function choose(stepType:StepType){setType(stepType);setValue({id:'new',step_order:version.steps.length+1,step_type:stepType,title:null,instruction:null,equipment:null,duration_seconds:null,temperature_celsius:null,batch_size:null,servings_per_tray:null,trays_per_batch:null,quantity_note:null,notes:null})}
  async function save(){if(!value)return;setBusy(true);setError('');try{const {id,...payload}=value;void id;onSaved(await apiRequest<Profile>(`/dishes/${dishId}/production-profile/versions/${version.id}/steps`,{method:'POST',body:JSON.stringify(payload)}));onCancel()}catch(cause){setError(friendlyError(cause,'製作步驟新增失敗'))}finally{setBusy(false)}}
  if(!type)return <section className="new-step-panel"><h4>這一步要做哪一類工作？</h4><p>先選類型，下一步只會顯示需要填寫的內容。</p><div className="step-type-grid">{Object.entries(steps).map(([key,label])=><button className="secondary" key={key} onClick={()=>choose(key as StepType)}>{label}</button>)}</div><button className="text-button" onClick={onCancel}>取消新增</button></section>
  return <section className="new-step-panel"><header><div><span className="eyebrow">新增步驟</span><h4>{steps[type]}</h4></div><button className="secondary" onClick={()=>{setType(null);setValue(null)}}>重新選擇</button></header>{value&&<StepFields value={value} onChange={setValue}/>} {error&&<Feedback type="error">{error}</Feedback>}<footer><button className="secondary" disabled={busy} onClick={onCancel}>取消</button><button disabled={busy||!value?.instruction?.trim()} onClick={()=>void save()}>{busy?'新增中…':'加入製作步驟'}</button></footer></section>
}

export function ProductionProfilePage({dish,isAdmin,onClose}:{dish:Dish;isAdmin:boolean;onClose:()=>void}){
  const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[notFound,setNotFound]=useState(false),[loadError,setLoadError]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const loadRequestId=useRef(0)
  const [tab,setTab]=useState<Tab>('basic'),[selected,setSelected]=useState(''),[imageUrl,setImageUrl]=useState('')
  const [wizard,setWizard]=useState(0),[maxBatch,setMaxBatch]=useState('100'),[notes,setNotes]=useState(''),[chosenServings,setChosenServings]=useState<number[]>([]),[customServing,setCustomServing]=useState('')
  const [newServing,setNewServing]=useState(''),[copyTarget,setCopyTarget]=useState<string|null>(null),[copyServing,setCopyServing]=useState(''),[addingStep,setAddingStep]=useState(false)
  const [previewServings,setPreviewServings]=useState(''),[preview,setPreview]=useState<Plan|null>(null)
  useEffect(()=>{
    const requestId=++loadRequestId.current,controller=new AbortController()
    setLoading(true);setProfile(null);setNotFound(false);setLoadError('');setError('');setMessage('');setWizard(0);setSelected('')
    void resolveProfileLoad(()=>apiRequest<Profile>(`/dishes/${dish.id}/production-profile`,{signal:controller.signal})).then(result=>{
      if(requestId!==loadRequestId.current)return
      if(result.kind==='found'){
        const value=result.profile;setProfile(value);setMaxBatch(String(value.max_batch_size));setNotes(value.notes??'');setSelected(value.versions[0]?.id??'')
      }else if(result.kind==='not-found')setNotFound(true)
      else if(!(result.cause instanceof DOMException&&result.cause.name==='AbortError'))setLoadError('標準食譜卡載入失敗，請稍後重試。')
    }).finally(()=>{if(requestId===loadRequestId.current)setLoading(false)})
    return()=>{controller.abort();if(requestId===loadRequestId.current)loadRequestId.current+=1}
  },[dish.id])
  useEffect(()=>{if(!profile?.has_image){setImageUrl('');return}let url='';void apiBlobUrl(`/dishes/${dish.id}/production-profile/image`).then(value=>{url=value;setImageUrl(value)}).catch(()=>setImageUrl(''));return()=>{if(url)URL.revokeObjectURL(url)}},[dish.id,profile?.has_image,profile?.updated_at])
  const version=useMemo(()=>profile?.versions.find(item=>item.id===selected)??profile?.versions[0]??null,[profile,selected])
  function accept(value:Profile){setProfile(value);setNotFound(false);setSelected(current=>value.versions.some(item=>item.id===current)?current:value.versions[0]?.id??'')}
  async function createProfileAndVersions(){setBusy(true);setError('');try{let value=profile??await apiRequest<Profile>(`/dishes/${dish.id}/production-profile`,{method:'POST',body:JSON.stringify({max_batch_size:Number(maxBatch),notes:notes||null})});accept(value);for(const serving of [...chosenServings].sort((a,b)=>a-b)){if(value.versions.some(item=>item.serving_count===serving))continue;value=await apiRequest<Profile>(`/dishes/${dish.id}/production-profile/versions`,{method:'POST',body:JSON.stringify({serving_count:serving,name:null,is_official:true})});accept(value)}setWizard(3)}catch(cause){setError(friendlyError(cause,'標準食譜卡建立失敗，已完成的內容會保留，可直接重試。'))}finally{setBusy(false)}}
  async function saveProfile(){if(!profile)return;setBusy(true);setError('');try{accept(await apiRequest<Profile>(`/dishes/${dish.id}/production-profile`,{method:'PATCH',body:JSON.stringify({max_batch_size:Number(maxBatch),notes:notes||null})}));setMessage('基本設定已儲存')}catch(cause){setError(friendlyError(cause,'基本設定儲存失敗'))}finally{setBusy(false)}}
  async function addVersion(serving=Number(newServing)){if(!profile||!serving)return;setBusy(true);setError('');try{const value=await apiRequest<Profile>(`/dishes/${dish.id}/production-profile/versions`,{method:'POST',body:JSON.stringify({serving_count:serving,name:null,is_official:true})});accept(value);setSelected(value.versions.find(item=>item.serving_count===serving)?.id??'');setNewServing('');setMessage(`${serving} 人份已建立，食材用量已依標準配方帶入。`)}catch(cause){setError(friendlyError(cause,'常用份數新增失敗'))}finally{setBusy(false)}}
  async function versionAction(path:string,method:'POST'|'PATCH'|'DELETE',body?:unknown){setBusy(true);setError('');try{accept(await apiRequest<Profile>(path,{method,body:body===undefined?undefined:JSON.stringify(body)}))}catch(cause){setError(friendlyError(cause,'常用份數更新失敗'))}finally{setBusy(false)}}
  function moveStep(index:number,direction:-1|1){if(!version)return;const target=index+direction;if(target<0||target>=version.steps.length)return;const ordered=[...version.steps];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];setBusy(true);void apiRequest<Profile>(`/dishes/${dish.id}/production-profile/versions/${version.id}/steps/reorder`,{method:'PUT',body:JSON.stringify({ordered_ids:ordered.map(item=>item.id)})}).then(accept).catch(cause=>setError(friendlyError(cause,'步驟順序更新失敗'))).finally(()=>setBusy(false))}
  async function upload(file:File){const body=new FormData();body.append('file',file);setBusy(true);try{accept(await apiRequest<Profile>(`/dishes/${dish.id}/production-profile/image`,{method:'POST',body}))}catch{setError('照片上傳失敗，僅支援 JPEG、PNG、WEBP，最大 5 MB。')}finally{setBusy(false)}}
  async function generatePreview(){setBusy(true);setError('');try{setPreview(await apiRequest<Plan>(`/dishes/${dish.id}/production-profile/preview?servings=${previewServings}`))}catch(cause){setError(friendlyError(cause,'製作計畫預覽失敗'))}finally{setBusy(false)}}

  if(loading)return <section className="production-page"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><LoadingState label="標準食譜卡載入中…"/></section>
  if(loadError)return <section className="production-page"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><Feedback type="error">{loadError}</Feedback></section>
  if(notFound&&wizard===0)return <section className="production-page"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><div className="production-page-heading"><div><p className="eyebrow">標準食譜卡</p><h2>{dish.code}｜{dish.name}</h2><p>把每批人數、食材用量與廚房步驟整理成現場可直接照做的標準。</p></div></div><EmptyState title="尚未建立標準食譜卡" description={dish.recipe_ingredient_count?`這道菜已有 ${dish.recipe_ingredient_count} 項配料，建立時會自動帶入食材用量。`:'可以先建立基本資料；之後完成標準配方，食材就能自動帶入。'}/>{isAdmin&&<div className="empty-state-action"><button onClick={()=>setWizard(1)}>建立標準食譜卡</button></div>}</section>
  if(wizard>0)return <section className="production-page production-wizard"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><div className="production-page-heading"><div><p className="eyebrow">第一次建立</p><h2>{dish.code}｜{dish.name}</h2><p>跟著 4 個步驟，就能完成一張廚房可用的標準食譜卡。</p></div></div><Progress current={wizard}/>{error&&<Feedback type="error">{error}</Feedback>}<section className="production-work-card">{wizard===1&&<><h3>一次最多做幾人份？</h3><p>填入設備與人力在一批內可以穩定完成的最大份數。</p><label className="featured-field">最大單批人數<input autoFocus type="number" min="1" value={maxBatch} onChange={event=>setMaxBatch(event.target.value)}/><small>之後系統會依這個上限安排批次，不會讓單批超量。</small></label><footer><button disabled={!Number(maxBatch)} onClick={()=>setWizard(2)}>下一步：選擇常用份數</button></footer></>}{wizard===2&&<><h3>平常最常做哪些份數？</h3><p>可以複選。系統會依標準配方自動換算每個份數的食材用量。</p><div className="serving-choice-grid">{[10,30,50,100].filter(value=>value<=Number(maxBatch)).map(value=><button key={value} className={chosenServings.includes(value)?'selected secondary':'secondary'} aria-pressed={chosenServings.includes(value)} onClick={()=>setChosenServings(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value])}>{value} 人份</button>)}</div><div className="custom-serving"><label>其他份數<input type="number" min="1" max={maxBatch} value={customServing} onChange={event=>setCustomServing(event.target.value)}/></label><button className="secondary" disabled={!Number(customServing)||Number(customServing)>Number(maxBatch)} onClick={()=>{const value=Number(customServing);setChosenServings(current=>current.includes(value)?current:[...current,value]);setCustomServing('')}}>加入</button></div>{chosenServings.length>0&&<p className="selection-summary">已選擇：{[...chosenServings].sort((a,b)=>a-b).map(value=>`${value} 人份`).join('、')}</p>}<footer><button className="secondary" onClick={()=>setWizard(1)}>上一步</button><button disabled={busy||chosenServings.length===0} onClick={()=>void createProfileAndVersions()}>{busy?'建立中…':'下一步：確認食材用量'}</button></footer></>}{wizard===3&&profile&&<><h3>確認各份數的食材用量</h3><p>用量已依標準配方自動換算。請選擇份數檢查，需要時可直接修改。</p><VersionSelector profile={profile} selected={selected} onSelect={setSelected}/>{version&&<IngredientsTable dishId={dish.id} version={version} isAdmin={isAdmin} onSaved={accept}/>}<footer><button onClick={()=>setWizard(4)}>下一步：建立製作步驟</button></footer></>}{wizard===4&&profile&&version&&<><h3>建立廚房製作步驟</h3><p>先選工作類型，再填現場真正需要看的內容。之後仍可新增或調整。</p><VersionSelector profile={profile} selected={selected} onSelect={setSelected}/><StepsSection dishId={dish.id} version={version} isAdmin={isAdmin} adding={addingStep} setAdding={setAddingStep} onSaved={accept} onMove={moveStep}/><footer><button className="secondary" onClick={()=>setWizard(3)}>上一步</button><button onClick={()=>{setWizard(0);setTab('preview')}}>完成，查看標準食譜卡</button></footer></>}</section></section>
  if(!profile)return <section className="production-page"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><Feedback type="error">標準食譜卡狀態異常，請重新進入。</Feedback></section>
  return <section className="production-page"><nav className="recipe-breadcrumb" aria-label="麵包屑"><button className="back-link" onClick={onClose}>← 返回菜色管理</button><span>菜色管理</span><span aria-hidden="true">›</span><span>{dish.name}</span><span aria-hidden="true">›</span><strong>標準食譜卡</strong></nav><div className="production-page-heading"><div><p className="eyebrow">標準食譜卡／廚房標準製程</p><h2>{dish.code}｜{dish.name}</h2><p>依常用份數維護食材與步驟，製作前再用預覽確認拆批方式。</p></div>{imageUrl&&<img className="production-heading-photo" src={imageUrl} alt={`${dish.name} 成品照片`}/>}</div><nav className="production-tabs" aria-label="標準食譜卡內容">{(Object.keys(tabLabels) as Tab[]).map(key=><button key={key} className={tab===key?'active':''} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{tabLabels[key]}</button>)}</nav>{error&&<Feedback type="error">{error}</Feedback>}{message&&<Feedback type="success">{message}</Feedback>}
    {tab==='basic'&&<section className="production-work-card"><header><div><h3>基本設定</h3><p>設定單批上限與整張食譜卡都適用的提醒。</p></div></header><div className="production-basic-grid"><label>最大單批人數<input disabled={!isAdmin} type="number" min="1" value={maxBatch} onChange={event=>setMaxBatch(event.target.value)}/><small>每一批都不會超過這個人數。</small></label><label>整體注意事項<textarea disabled={!isAdmin} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="例如：出餐前確認中心溫度。"/></label></div><section className="production-photo-section"><h4>成品照片</h4>{imageUrl?<img className="production-photo" src={imageUrl} alt={`${dish.name} 成品照片`}/>:<p className="muted">尚未上傳成品照片。</p>}{isAdmin&&<div className="actions"><label className="file-button">{profile.has_image?'更換照片':'上傳照片'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/></label>{profile.has_image&&<button className="danger" disabled={busy} onClick={()=>void versionAction(`/dishes/${dish.id}/production-profile/image`,'DELETE')}>刪除照片</button>}</div>}</section>{isAdmin&&<footer><button disabled={busy||!Number(maxBatch)} onClick={()=>void saveProfile()}>{busy?'儲存中…':'儲存基本設定'}</button></footer>}</section>}
    {tab==='versions'&&<section className="production-work-card"><header><div><h3>常用製作份數</h3><p>可正式使用的份數會提供菜單製作計畫選用；編輯中的份數只供菜色管理時檢查。</p></div></header>{isAdmin&&<div className="add-serving-row"><label>新增份數<input type="number" min="1" max={profile.max_batch_size} value={newServing} onChange={event=>setNewServing(event.target.value)} placeholder="例如 80"/></label><button disabled={busy||!Number(newServing)} onClick={()=>void addVersion()}>新增常用份數</button></div>}{profile.versions.length===0?<EmptyState title="尚未建立常用份數" description="新增平常最常製作的人數，系統會自動帶入食材用量。"/>:<div className="version-card-grid">{profile.versions.map(item=><article className={`version-card ${item.id===selected?'selected':''}`} key={item.id}><header><div><strong>{item.serving_count} 人份</strong><span className={item.is_official?'status-badge':'status-badge warning'}>{item.is_official?'可正式使用':'編輯中'}</span></div><small>{item.ingredients.length} 項食材・{item.steps.length} 個步驟</small></header>{item.name&&<p>{item.name}</p>}<footer><button onClick={()=>{setSelected(item.id);setTab('ingredients')}}>查看／編輯</button>{isAdmin&&<><button className="secondary" onClick={()=>{setCopyTarget(copyTarget===item.id?null:item.id);setCopyServing('')}}>複製</button><button className="secondary" disabled={busy} onClick={()=>void versionAction(`/dishes/${dish.id}/production-profile/versions/${item.id}`,'PATCH',{is_official:!item.is_official})}>{item.is_official?'改成編輯中':'設為可正式使用'}</button><button className="danger" disabled={busy} onClick={()=>{if(window.confirm(`確定刪除 ${item.serving_count} 人份？`))void versionAction(`/dishes/${dish.id}/production-profile/versions/${item.id}`,'DELETE')}}>刪除</button></>}</footer>{copyTarget===item.id&&<div className="copy-serving-row"><label>複製成幾人份<input autoFocus type="number" min="1" max={profile.max_batch_size} value={copyServing} onChange={event=>setCopyServing(event.target.value)}/></label><button disabled={!Number(copyServing)||busy} onClick={()=>void versionAction(`/dishes/${dish.id}/production-profile/versions/${item.id}/copy`,'POST',{serving_count:Number(copyServing),is_official:false})}>建立編輯中版本</button></div>}</article>)}</div>}</section>}
    {tab==='ingredients'&&<section className="production-work-card"><header><div><h3>食材用量</h3><p>選擇一個常用份數，查看從標準配方換算後的食材用量。</p></div></header>{profile.versions.length===0?<EmptyState title="目前沒有可編輯的份數" description="請先到「常用製作份數」新增一個份數。"/>:<><VersionSelector profile={profile} selected={version?.id??''} onSelect={setSelected}/>{version&&<IngredientsTable dishId={dish.id} version={version} isAdmin={isAdmin} onSaved={accept}/>}</>}</section>}
    {tab==='steps'&&<section className="production-work-card"><header><div><h3>製作步驟</h3><p>步驟先以摘要顯示；需要調整時再展開，不必一次面對所有欄位。</p></div></header>{profile.versions.length===0?<EmptyState title="目前沒有可編輯的份數" description="請先建立常用製作份數。"/>:<><VersionSelector profile={profile} selected={version?.id??''} onSelect={setSelected}/>{version&&<StepsSection dishId={dish.id} version={version} isAdmin={isAdmin} adding={addingStep} setAdding={setAddingStep} onSaved={accept} onMove={moveStep}/>}</>}</section>}
    {tab==='preview'&&<section className="production-work-card"><header><div><h3>製作計畫預覽</h3><p>輸入今日供餐人數，確認要分成幾批以及每批人數。</p></div></header><div className="preview-input-row"><label>今日供餐人數<input type="number" min="1" value={previewServings} onChange={event=>setPreviewServings(event.target.value)}/></label><button disabled={busy||!Number(previewServings)} onClick={()=>void generatePreview()}>{busy?'計算中…':'產生預覽'}</button></div>{preview?<ProductionPlanSummary preview={preview} maxBatch={profile.max_batch_size} officialServings={profile.versions.filter(item=>item.is_official).map(item=>item.serving_count)}/>:<EmptyState title="尚未產生預覽" description="輸入今日供餐人數後，系統會依正式的常用份數安排批次。"/>}</section>}
  </section>
}

function VersionSelector({profile,selected,onSelect}:{profile:Profile;selected:string;onSelect:(id:string)=>void}){return <div className="version-selector" role="group" aria-label="選擇製作份數">{profile.versions.map(item=><button key={item.id} className={selected===item.id?'active':''} aria-pressed={selected===item.id} onClick={()=>onSelect(item.id)}>{item.serving_count} 人份 <small>{item.is_official?'已確認':'編輯中'}</small></button>)}</div>}

function IngredientsTable({dishId,version,isAdmin,onSaved}:{dishId:string;version:Version;isAdmin:boolean;onSaved:(value:Profile)=>void}){return version.ingredients.length===0?<EmptyState title="尚未帶入食材" description="請先完成這道菜的標準配方，再建立或重新建立常用份數。"/>:<TableFrame><table className="production-ingredients-table"><thead><tr><th>食材</th><th>這個份數需要</th><th>單位</th><th>用途</th><th>現場提醒</th><th>操作</th></tr></thead><tbody>{version.ingredients.map(item=><IngredientEditor key={item.id} dishId={dishId} versionId={version.id} item={item} isAdmin={isAdmin} onSaved={onSaved}/>)}</tbody></table></TableFrame>}

function StepsSection({dishId,version,isAdmin,adding,setAdding,onSaved,onMove}:{dishId:string;version:Version;isAdmin:boolean;adding:boolean;setAdding:(value:boolean)=>void;onSaved:(value:Profile)=>void;onMove:(index:number,direction:-1|1)=>void}){return <div className="steps-section">{version.steps.length===0&&!adding&&<EmptyState title="尚未建立製作步驟" description="從第一個動作開始，例如清洗、切配、醃製或加熱。"/>}{version.steps.map((item,index)=><StepCard key={item.id} dishId={dishId} versionId={version.id} item={item} index={index} count={version.steps.length} isAdmin={isAdmin} onSaved={onSaved} onMove={direction=>onMove(index,direction)}/>)}{adding?<NewStep dishId={dishId} version={version} onSaved={onSaved} onCancel={()=>setAdding(false)}/>:isAdmin&&<button className="add-step-button" onClick={()=>setAdding(true)}>＋ 新增製作步驟</button>}</div>}

function ProductionPlanSummary({preview,maxBatch,officialServings}:{preview:Plan;maxBatch:number;officialServings:number[]}){const groups=aggregateBatches(preview.batches);return <section className="production-plan-summary"><header><div><span>今日總供餐</span><strong>{preview.diner_count} 人</strong></div><div><span>共需製作</span><strong>{preview.batch_count} 批</strong></div><div><span>單批上限</span><strong>{maxBatch} 人</strong></div></header><p>正式常用份數：{officialServings.length?[...officialServings].sort((a,b)=>b-a).map(value=>`${value} 人份`).join('、'):'尚未設定'}</p><div className="batch-summary-list">{groups.map(group=><article key={`${group.serving_count}-${group.official}`}><strong>{group.serving_count} 人份 × {group.count} 批</strong><span className={group.official?'status-badge':'status-badge warning'}>{group.official?'使用正式版本':'需要估算，請確認'}</span></article>)}</div></section>}
