import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { apiRequest } from '../../api/client'
import { DishOption, List, MealType, Menu, MenuAggregate, MenuDish, MenuSlot } from './types'

const key=(date:string,mealId:string)=>`${date}:${mealId}`
interface Paged<T>{items:T[];pagination:{page:number;page_size:number;total:number}}

export function MenuEditor({menu,onClose}:{menu:Menu;onClose:()=>void}){
  const [data,setData]=useState<MenuAggregate|null>(null);const [dishes,setDishes]=useState<DishOption[]>([]);const [menus,setMenus]=useState<Menu[]>([])
  const [slots,setSlots]=useState<Record<string,MenuSlot>>({});const [candidates,setCandidates]=useState<Record<string,string>>({})
  const [mealName,setMealName]=useState('');const [mealDrafts,setMealDrafts]=useState<Record<string,string>>({})
  const [dishSearch,setDishSearch]=useState('');const [dishPage,setDishPage]=useState(1);const [dishTotal,setDishTotal]=useState(0)
  const [showDiners,setShowDiners]=useState(true);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false)
  const [error,setError]=useState('');const [message,setMessage]=useState('')
  const [sourceMenu,setSourceMenu]=useState(menu.id);const [sourceDate,setSourceDate]=useState(menu.start_date);const [destinationDate,setDestinationDate]=useState(menu.start_date);const [copyMode,setCopyMode]=useState<'add'|'replace'>('add')
  const [confirmReplace,setConfirmReplace]=useState(false)
  const load=useCallback(async()=>{setLoading(true);try{const [aggregate,menuList]=await Promise.all([apiRequest<MenuAggregate>(`/menus/${menu.id}/editor`),apiRequest<List<Menu>>('/menus?active=true&page_size=100')]);setData(aggregate);setMenus(menuList.items);setMealDrafts(Object.fromEntries(aggregate.meal_types.map(m=>[m.id,m.name])));setSlots(Object.fromEntries(aggregate.slots.map(slot=>[key(slot.menu_date,slot.menu_meal_type_id),slot])));setError('')}catch{setError('菜單工作區載入失敗')}finally{setLoading(false)}},[menu.id])
  const loadDishes=useCallback(async()=>{try{const result=await apiRequest<Paged<DishOption>>(`/dishes?active=true&page=${dishPage}&page_size=25&search=${encodeURIComponent(dishSearch)}`);setDishes(result.items);setDishTotal(result.pagination.total)}catch{setError('菜色候選載入失敗')}},[dishPage,dishSearch])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{void loadDishes()},[loadDishes])
  const visibleMeals=useMemo(()=>data?.meal_types.filter(m=>m.is_active||Object.values(slots).some(slot=>slot.menu_meal_type_id===m.id))??[],[data,slots])
  function slotFor(date:string,meal:MealType){return slots[key(date,meal.id)]??{menu_date:date,menu_meal_type_id:meal.id,notes:null,dishes:[]}}
  function setSlot(slot:MenuSlot){setSlots(current=>({...current,[key(slot.menu_date,slot.menu_meal_type_id)]:slot}))}
  function addDish(date:string,meal:MealType){const slot=slotFor(date,meal);const dishId=candidates[key(date,meal.id)];const dish=dishes.find(item=>item.id===dishId);if(!dish||slot.dishes.some(item=>item.dish_id===dish.id))return;setSlot({...slot,dishes:[...slot.dishes,{dish_id:dish.id,dish_code:dish.code,dish_name:dish.name,diner_count:1,notes:null,sort_order:slot.dishes.length+1}]})}
  function updateDish(slot:MenuSlot,index:number,changes:Partial<MenuDish>){setSlot({...slot,dishes:slot.dishes.map((item,i)=>i===index?{...item,...changes}:item)})}
  function removeDish(slot:MenuSlot,index:number){setSlot({...slot,dishes:slot.dishes.filter((_,i)=>i!==index).map((item,i)=>({...item,sort_order:i+1}))})}
  async function save(){setSaving(true);setMessage('');try{const payload=Object.values(slots).filter(slot=>slot.menu_day_id||slot.notes||slot.dishes.length).map(slot=>({...slot,dishes:slot.dishes.map(({id,dish_id,diner_count,notes,sort_order})=>({id,dish_id,diner_count,notes,sort_order}))}));const saved=await apiRequest<MenuAggregate>(`/menus/${menu.id}/editor`,{method:'PUT',body:JSON.stringify({slots:payload})});setData(saved);setSlots(Object.fromEntries(saved.slots.map(slot=>[key(slot.menu_date,slot.menu_meal_type_id),slot])));setMessage('完整菜單已在單一交易中儲存');setError('')}catch{setError('儲存失敗；所有變更均已 rollback，請檢查停用資料、重複菜色與數值')}finally{setSaving(false)}}
  async function addMeal(event:FormEvent){event.preventDefault();try{await apiRequest(`/menus/${menu.id}/meal-types`,{method:'POST',body:JSON.stringify({name:mealName,sort_order:(data?.meal_types.length??0)+1})});setMealName('');await load()}catch{setError('餐別新增失敗，名稱不可重複')}}
  async function saveMeal(meal:MealType){try{await apiRequest(`/menus/${menu.id}/meal-types/${meal.id}`,{method:'PATCH',body:JSON.stringify({name:mealDrafts[meal.id]})});await load()}catch{setError('餐別修改失敗')}}
  async function toggleMeal(meal:MealType){try{await apiRequest(`/menus/${menu.id}/meal-types/${meal.id}/${meal.is_active?'deactivate':'reactivate'}`,{method:'POST'});await load()}catch{setError('餐別狀態更新失敗')}}
  async function moveMeal(meal:MealType,direction:-1|1){if(!data)return;const ordered=[...data.meal_types].sort((a,b)=>a.sort_order-b.sort_order);const index=ordered.findIndex(item=>item.id===meal.id),target=index+direction;if(target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];try{await apiRequest(`/menus/${menu.id}/meal-types/reorder`,{method:'PUT',body:JSON.stringify({ordered_ids:ordered.map(item=>item.id)})});await load()}catch{setError('餐別排序失敗')}}
  async function copyDay(){try{const copied=await apiRequest<MenuAggregate>(`/menus/${menu.id}/copy-day`,{method:'POST',body:JSON.stringify({source_menu_id:sourceMenu,source_date:sourceDate,destination_date:destinationDate,mode:copyMode,confirm_replace:confirmReplace})});setData(copied);setSlots(Object.fromEntries(copied.slots.map(slot=>[key(slot.menu_date,slot.menu_meal_type_id),slot])));setMessage('日期複製完成');setConfirmReplace(false)}catch{setError('日期複製失敗；請確認日期、餐別名稱、停用資料與覆蓋確認')}}
  async function copyWeek(){try{const copied=await apiRequest<MenuAggregate>(`/menus/${menu.id}/copy-week`,{method:'POST',body:JSON.stringify({source_menu_id:sourceMenu,mode:copyMode,confirm_replace:confirmReplace})});setData(copied);setSlots(Object.fromEntries(copied.slots.map(slot=>[key(slot.menu_date,slot.menu_meal_type_id),slot])));setMessage('完整七日複製完成');setConfirmReplace(false)}catch{setError('整週複製只支援來源與目的皆為完整七日，餐別須匹配，覆蓋須確認')}}
  if(loading||!data)return <section><button onClick={onClose}>返回菜單</button><p>{loading?'載入中…':error}</p></section>
  return <section><div className="section-heading"><div><p className="eyebrow">Menu Editor</p><h2>{data.menu.name}</h2><p>{data.menu.start_date} ～ {data.menu.end_date}</p></div><div className="actions"><label className="inline-check"><input type="checkbox" checked={showDiners} onChange={e=>setShowDiners(e.target.checked)}/>顯示用餐人數</label><button onClick={onClose}>返回菜單</button></div></div>
    {error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}
    <section className="menu-tools"><h3>自訂餐別</h3><form className="inline-form" onSubmit={addMeal}><input value={mealName} onChange={e=>setMealName(e.target.value)} placeholder="例如：早點、晚點" required/><button>新增餐別</button></form><div className="meal-list">{data.meal_types.map(meal=><div key={meal.id} className={!meal.is_active?'inactive':''}><input value={mealDrafts[meal.id]??meal.name} onChange={e=>setMealDrafts({...mealDrafts,[meal.id]:e.target.value})}/><span>順序 {meal.sort_order}</span><button onClick={()=>void moveMeal(meal,-1)}>↑</button><button onClick={()=>void moveMeal(meal,1)}>↓</button><button onClick={()=>void saveMeal(meal)}>儲存名稱</button><button onClick={()=>void toggleMeal(meal)}>{meal.is_active?'停用':'恢復'}</button></div>)}</div></section>
    <div className="toolbar"><label>搜尋候選菜色<input value={dishSearch} onChange={e=>{setDishSearch(e.target.value);setDishPage(1)}}/></label><label>候選頁碼<input type="number" min="1" max={Math.max(1,Math.ceil(dishTotal/25))} value={dishPage} onChange={e=>setDishPage(Math.max(1,Number(e.target.value)))}/></label><span>候選共 {dishTotal} 筆</span><button disabled={dishPage<=1} onClick={()=>setDishPage(value=>value-1)}>上一頁</button><button disabled={dishPage>=Math.ceil(dishTotal/25)} onClick={()=>setDishPage(value=>value+1)}>下一頁</button></div>
    {!visibleMeals.length?<p>請先建立至少一個啟用餐別。</p>:<div className="menu-matrix"><table><thead><tr><th className="sticky-col">餐別</th>{data.dates.map(date=><th key={date}>{date}</th>)}</tr></thead><tbody>{visibleMeals.map(meal=><tr key={meal.id}><th className="sticky-col">{meal.name}{!meal.is_active&&<small>已停用（歷史）</small>}</th>{data.dates.map(date=>{const slot=slotFor(date,meal);const slotKey=key(date,meal.id);return <td key={date} className="meal-cell"><label>餐格備註<input value={slot.notes??''} onChange={e=>setSlot({...slot,notes:e.target.value||null})}/></label>{slot.dishes.map((dish,index)=><div key={dish.id??dish.dish_id} className="scheduled-dish"><strong>{dish.dish_code}｜{dish.dish_name}</strong>{showDiners&&<label>人數<input type="number" min="0" value={dish.diner_count} onChange={e=>updateDish(slot,index,{diner_count:Number(e.target.value)})}/></label>}<label>順序<input type="number" min="1" value={dish.sort_order} onChange={e=>updateDish(slot,index,{sort_order:Number(e.target.value)})}/></label><label>備註<input value={dish.notes??''} onChange={e=>updateDish(slot,index,{notes:e.target.value||null})}/></label><button className="danger" onClick={()=>removeDish(slot,index)}>移除關聯</button></div>)}{meal.is_active?<div className="inline-form"><select value={candidates[slotKey]??''} onChange={e=>setCandidates({...candidates,[slotKey]:e.target.value})}><option value="">選擇目前候選頁菜色</option>{dishes.filter(d=>!slot.dishes.some(current=>current.dish_id===d.id)).map(d=><option key={d.id} value={d.id}>{d.code}｜{d.name}</option>)}</select><button onClick={()=>addDish(date,meal)} disabled={!candidates[slotKey]}>加入</button></div>:<small>停用餐別不可加入新菜色</small>}</td>})}</tr>)}</tbody></table></div>}
    <div className="editor-save"><button onClick={()=>void save()} disabled={saving}>{saving?'儲存中…':'儲存完整菜單'}</button></div>
    <section className="menu-tools"><h3>Menu Copy</h3><div className="copy-form"><label>來源菜單<select value={sourceMenu} onChange={e=>setSourceMenu(e.target.value)}>{menus.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>來源日期<input type="date" value={sourceDate} onChange={e=>setSourceDate(e.target.value)}/></label><label>目的日期<input type="date" value={destinationDate} onChange={e=>setDestinationDate(e.target.value)}/></label><label>模式<select value={copyMode} onChange={e=>{setCopyMode(e.target.value as 'add'|'replace');setConfirmReplace(false)}}><option value="add">加入（跳過重複）</option><option value="replace">覆蓋目的日期</option></select></label>{copyMode==='replace'&&<label className="inline-check"><input type="checkbox" checked={confirmReplace} onChange={e=>setConfirmReplace(e.target.checked)}/>我確認覆蓋目的資料</label>}<button onClick={()=>void copyDay()} disabled={copyMode==='replace'&&!confirmReplace}>複製一天</button><button onClick={()=>void copyWeek()} disabled={copyMode==='replace'&&!confirmReplace}>複製完整七日</button></div></section>
  </section>
}
