import { FormEvent, useCallback, useEffect, useState } from 'react'
import { apiRequest } from '../../api/client'
import { CaseDetail, CaseStatus, DeliveryType, Meal, PostpartumCase, PreparationMode, ServicePause } from './types'
import { postpartumWeek, postpartumWeekRanges } from './timeline'

const meals:{value:Meal,label:string}[]=[{value:'breakfast',label:'早餐'},{value:'lunch',label:'午餐'},{value:'dinner',label:'晚餐'}]
const statuses:{value:CaseStatus,label:string}[]=[{value:'pending',label:'未起伙'},{value:'active',label:'供餐中'},{value:'paused',label:'暫停'},{value:'ended',label:'已停伙'}]
const modes:{value:PreparationMode,label:string}[]=[{value:'no_herbal',label:'不中藥'},{value:'herbal',label:'要中藥'},{value:'rice_wine_sesame',label:'米酒水＋麻油'},{value:'no_rice_wine_sesame',label:'不米酒水＋麻油'}]
type EndMeal=Meal|''
interface CaseFormState {case_number:string;name:string;current_room:string;delivery_type:DeliveryType;delivery_date:string;service_start_date:string;service_start_meal:Meal;service_end_date:string;service_end_meal:EndMeal;status:CaseStatus;preparation_mode:PreparationMode;service_note:string}
interface Paged<T>{items:T[];pagination:{page:number;page_size:number;total:number}}
const emptyCaseForm=():CaseFormState=>({case_number:'',name:'',current_room:'',delivery_type:'vaginal',delivery_date:'',service_start_date:'',service_start_meal:'breakfast',service_end_date:'',service_end_meal:'',status:'pending',preparation_mode:'no_herbal',service_note:''})
const editFormFrom=(item:PostpartumCase):CaseFormState=>({case_number:item.case_number,name:item.name,current_room:item.current_room,delivery_type:item.delivery_type,delivery_date:item.delivery_date,service_start_date:item.service_start_date,service_start_meal:item.service_start_meal,service_end_date:item.service_end_date??'',service_end_meal:item.service_end_meal??'',status:item.status,preparation_mode:item.preparation_mode,service_note:item.service_note??''})
const payloadFrom=(form:CaseFormState)=>({...form,service_end_date:form.service_end_date||null,service_end_meal:form.service_end_date?(form.service_end_meal||null):null,service_note:form.service_note||null})

function CaseFields({form,setForm,includeRoom}:{form:CaseFormState;setForm:(value:CaseFormState)=>void;includeRoom:boolean}){
  return <>
    <label>號碼<input value={form.case_number} onChange={e=>setForm({...form,case_number:e.target.value})} required/></label>
    <label>姓名<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>
    {includeRoom&&<label>房號／床號<input value={form.current_room} onChange={e=>setForm({...form,current_room:e.target.value})} required/></label>}
    <label>生產方式<select value={form.delivery_type} onChange={e=>setForm({...form,delivery_type:e.target.value as DeliveryType})}><option value="vaginal">自然產</option><option value="cesarean">剖腹產</option></select></label>
    <label>生產日期<input type="date" value={form.delivery_date} onChange={e=>setForm({...form,delivery_date:e.target.value})} required/></label>
    <label>起伙日期<input type="date" value={form.service_start_date} onChange={e=>setForm({...form,service_start_date:e.target.value})} required/></label>
    <label>起伙餐別<select value={form.service_start_meal} onChange={e=>setForm({...form,service_start_meal:e.target.value as Meal})}>{meals.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>
    <label>停伙日期<input type="date" value={form.service_end_date} onChange={e=>setForm({...form,service_end_date:e.target.value,service_end_meal:e.target.value?form.service_end_meal:''})}/></label>
    <label>停伙餐別<select value={form.service_end_meal} disabled={!form.service_end_date} onChange={e=>setForm({...form,service_end_meal:e.target.value as EndMeal})}><option value="">未設定</option>{meals.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>
    <label>供餐狀態<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as CaseStatus})}>{statuses.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>
    <label>調理方式<select value={form.preparation_mode} onChange={e=>setForm({...form,preparation_mode:e.target.value as PreparationMode})}>{modes.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>
    <label>供餐備註<textarea value={form.service_note} onChange={e=>setForm({...form,service_note:e.target.value})}/></label>
  </>
}

export function PostpartumCasesPage(){
  const [items,setItems]=useState<PostpartumCase[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState(''),[activeFilter,setActiveFilter]=useState('true')
  const [createForm,setCreateForm]=useState<CaseFormState>(emptyCaseForm),[editingCase,setEditingCase]=useState<PostpartumCase|null>(null),[editForm,setEditForm]=useState<CaseFormState|null>(null),[detail,setDetail]=useState<CaseDetail|null>(null)
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[editError,setEditError]=useState('')
  const [room,setRoom]=useState(''),[roomDate,setRoomDate]=useState(''),[roomMeal,setRoomMeal]=useState<Meal>('breakfast'),[roomError,setRoomError]=useState('')
  const [pause,setPause]=useState({start_date:'',start_meal:'breakfast' as Meal,end_date:'',end_meal:'dinner' as Meal,note:''}),[editingPause,setEditingPause]=useState<ServicePause|null>(null)
  const pages=Math.max(1,Math.ceil(total/25))
  const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({page:String(page),page_size:'25'});if(search)q.set('search',search);if(statusFilter)q.set('status',statusFilter);if(activeFilter)q.set('active',activeFilter);const data=await apiRequest<Paged<PostpartumCase>>(`/postpartum/cases?${q}`);setItems(data.items);setTotal(data.pagination.total);setError('')}catch{setError('個案資料載入失敗')}finally{setLoading(false)}},[activeFilter,page,search,statusFilter])
  useEffect(()=>{void load()},[load])
  async function refreshDetail(id:string){setDetail(await apiRequest<CaseDetail>(`/postpartum/cases/${id}`))}
  function openEdit(item:PostpartumCase){setEditingCase(item);setEditForm(editFormFrom(item));setEditError('')}
  function closeEdit(){setEditingCase(null);setEditForm(null);setEditError('')}
  async function createCase(event:FormEvent){event.preventDefault();setError('');try{await apiRequest('/postpartum/cases',{method:'POST',body:JSON.stringify(payloadFrom(createForm))});setCreateForm(emptyCaseForm());setMessage('個案已建立');await load()}catch{setError('儲存失敗，請檢查日期、餐別與必填欄位')}}
  async function saveEdit(event:FormEvent){event.preventDefault();if(!editingCase||!editForm)return;setEditError('');const {current_room,...payload}=payloadFrom(editForm);void current_room;try{await apiRequest(`/postpartum/cases/${editingCase.id}`,{method:'PATCH',body:JSON.stringify(payload)});closeEdit();setMessage('個案已更新');await load()}catch{setEditError('修改失敗，請檢查日期、餐別與必填欄位')}}
  async function toggle(item:PostpartumCase){await apiRequest(`/postpartum/cases/${item.id}/${item.is_active?'deactivate':'reactivate'}`,{method:'POST'});await load()}
  async function addRoom(event:FormEvent){event.preventDefault();if(!detail)return;setRoomError('');try{await apiRequest(`/postpartum/cases/${detail.case.id}/room-changes`,{method:'POST',body:JSON.stringify({room,effective_date:roomDate,effective_meal:roomMeal})});setRoom('');setRoomDate('');await refreshDetail(detail.case.id);await load()}catch{setRoomError('房號異動失敗，請確認房號與異動日期。')}}
  async function savePause(event:FormEvent){event.preventDefault();if(!detail)return;const path=editingPause?`/postpartum/cases/${detail.case.id}/pauses/${editingPause.id}`:`/postpartum/cases/${detail.case.id}/pauses`;await apiRequest(path,{method:editingPause?'PATCH':'POST',body:JSON.stringify({...pause,note:pause.note||null})});setPause({start_date:'',start_meal:'breakfast',end_date:'',end_meal:'dinner',note:''});setEditingPause(null);await refreshDetail(detail.case.id)}
  async function removePause(id:string){if(!detail)return;await apiRequest(`/postpartum/cases/${detail.case.id}/pauses/${id}`,{method:'DELETE'});await refreshDetail(detail.case.id)}
  return <section><h2>月子餐個案管理</h2>
    <form className="panel-form" onSubmit={createCase}><CaseFields form={createForm} setForm={setCreateForm} includeRoom/><button>新增個案</button></form>
    <div className="toolbar"><label>搜尋<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="編號、姓名或房號"/></label><label>狀態<select value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1)}}><option value="">全部</option>{statuses.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>資料<select value={activeFilter} onChange={e=>{setActiveFilter(e.target.value);setPage(1)}}><option value="true">啟用</option><option value="false">停用</option><option value="">全部</option></select></label><button type="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一頁</button><span>{page} / {pages}（共 {total} 筆）</span><button type="button" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>下一頁</button></div>
    {error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}{loading?<p>載入中…</p>:<table><thead><tr><th>號碼</th><th>房號／床號</th><th>姓名</th><th>生產方式</th><th>生產日期</th><th>目前週次</th><th>起伙／停伙</th><th>供餐狀態</th><th>調理方式</th><th>供餐備註</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.case_number}</td><td>{item.current_room}</td><td>{item.name}</td><td>{item.delivery_type==='vaginal'?'自然產':'剖腹產'}</td><td>{item.delivery_date}</td><td>{postpartumWeek(item.delivery_date)}</td><td>{item.service_start_date} {meals.find(x=>x.value===item.service_start_meal)?.label} ～ {item.service_end_date?`${item.service_end_date} ${meals.find(x=>x.value===item.service_end_meal)?.label}`:'未定'}</td><td>{statuses.find(x=>x.value===item.status)?.label}{!item.is_active?'（停用）':''}</td><td>{modes.find(x=>x.value===item.preparation_mode)?.label}</td><td>{item.service_note||'—'}</td><td className="actions"><button onClick={()=>void refreshDetail(item.id)}>檢視</button><button onClick={()=>openEdit(item)}>修改</button><button onClick={()=>void toggle(item)}>{item.is_active?'停用':'恢復'}</button></td></tr>)}</tbody></table>}
    {editingCase&&editForm&&<div className="modal-backdrop" onMouseDown={closeEdit}><section className="modal-panel" role="dialog" aria-modal="true" aria-labelledby="edit-postpartum-title" onMouseDown={event=>event.stopPropagation()}><header><h2 id="edit-postpartum-title">修改月子餐個案</h2><button className="secondary" onClick={closeEdit}>關閉</button></header><form className="panel-form" onSubmit={saveEdit}><CaseFields form={editForm} setForm={setEditForm} includeRoom={false}/>{editError&&<p className="error">{editError}</p>}<footer><button>儲存修改</button><button type="button" className="secondary" onClick={closeEdit}>取消</button></footer></form><p>房號異動請至個案檢視內使用「新增房號異動」，以保留完整歷程。</p></section></div>}
    {detail&&<div className="modal-backdrop" onMouseDown={()=>setDetail(null)}><section className="modal-panel" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}>
      <header><div><h2>{detail.case.name}｜{detail.case.case_number}</h2><p>目前房號：{detail.case.current_room}</p></div><button className="secondary" onClick={()=>setDetail(null)}>關閉</button></header><p>生產方式：{detail.case.delivery_type==='vaginal'?'自然產':'剖腹產'}｜生產日期：{detail.case.delivery_date}｜目前週次：{postpartumWeek(detail.case.delivery_date)}</p>
      <h3>產後週次</h3><ul>{postpartumWeekRanges(detail.case.delivery_date).map(x=><li key={x.week}>第 {x.week} 週：{x.from} ～ {x.to}</li>)}</ul><p>起伙：{detail.case.service_start_date} {meals.find(x=>x.value===detail.case.service_start_meal)?.label}｜停伙：{detail.case.service_end_date?`${detail.case.service_end_date} ${meals.find(x=>x.value===detail.case.service_end_meal)?.label}`:'未定'}｜{modes.find(x=>x.value===detail.case.preparation_mode)?.label}</p><p>{detail.case.service_note||'無供餐備註'}</p>
      <h3>房號歷程</h3><ul>{detail.room_history.map(x=><li key={x.id}>{x.effective_date} {meals.find(m=>m.value===x.effective_meal)?.label}：{x.room}</li>)}</ul><form className="panel-form" onSubmit={addRoom}><label>新房號<input value={room} onChange={e=>setRoom(e.target.value)} required/></label><label>異動日期<input type="date" value={roomDate} onChange={e=>setRoomDate(e.target.value)} required/></label><label>異動餐別<select value={roomMeal} onChange={e=>setRoomMeal(e.target.value as Meal)}>{meals.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{roomError&&<p className="error">{roomError}</p>}<button>新增房號異動</button></form>
      <h3>暫停服務紀錄</h3><ul>{detail.pauses.map(x=><li key={x.id}>{x.start_date} {meals.find(m=>m.value===x.start_meal)?.label} ～ {x.end_date} {meals.find(m=>m.value===x.end_meal)?.label}　{x.note}<button className="secondary" onClick={()=>{setEditingPause(x);setPause({start_date:x.start_date,start_meal:x.start_meal,end_date:x.end_date,end_meal:x.end_meal,note:x.note??''})}}>修改</button><button className="danger" onClick={()=>void removePause(x.id)}>刪除</button></li>)}</ul><form className="panel-form" onSubmit={savePause}><label>暫停開始<input type="date" value={pause.start_date} onChange={e=>setPause({...pause,start_date:e.target.value})} required/></label><label>餐別<select value={pause.start_meal} onChange={e=>setPause({...pause,start_meal:e.target.value as Meal})}>{meals.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>暫停結束<input type="date" value={pause.end_date} onChange={e=>setPause({...pause,end_date:e.target.value})} required/></label><label>餐別<select value={pause.end_meal} onChange={e=>setPause({...pause,end_meal:e.target.value as Meal})}>{meals.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>備註<input value={pause.note} onChange={e=>setPause({...pause,note:e.target.value})}/></label><button>{editingPause?'儲存暫停修改':'新增暫停紀錄'}</button></form>
    </section></div>}
  </section>
}
