import { FormEvent, useState } from 'react'
import { apiDownload, apiRequest } from '../../api/client'
import { AnomalyGroups } from '../../components/anomalies/AnomalyGroups'
import { groupAnomalies,type Anomaly } from '../../components/anomalies/anomalies'
import { Menu } from '../menus/types'
import { buildTsv,dailyRowsTsv,filterSupplierRows,sortDailyRows,supplierOptions,supplierRowsTsv,type DailyRequirementRow } from './dailyRequirements'
import { formatMoney,formatQuantity,plainDecimal } from '../../utils/numbers'
import { writeClipboard } from '../../utils/clipboard'
import { PaginationControls } from '../../components/ui/PaginationControls'
import { dateRangeError,menuCandidateDateParams,preserveSelected } from '../../utils/listQuery'
import { useMenuCandidates } from '../menus/useMenuCandidates'

interface Row { row_key:string; ingredient_code:string; ingredient_name:string; supplier_name:string|null; requirement_quantity:string; requirement_unit:string; suggested_purchase_quantity:string|null; suggested_purchase_unit:string|null; configured_purchase_unit:string|null; package_size:string; minimum_order_quantity:string; current_price:string|null; estimated_cost:string|null; needs_review:boolean }
interface Result { rows:Row[]; daily_rows:DailyRequirementRow[]; known_estimated_cost:string; total_estimated_cost:string|null; anomalies:Anomaly[]; anomaly_summary:{total:number;errors:number;warnings:number} }
type RangeMode='all'|'custom'
export function RequirementsPage() {
  const [selectedMenuMap,setSelectedMenuMap]=useState<Map<string,Menu>>(new Map())
  const [menuSearchStart,setMenuSearchStart]=useState(''),[menuSearchEnd,setMenuSearchEnd]=useState('')
  const menuSearchError=dateRangeError(menuSearchStart,menuSearchEnd)
  const menuCandidates=useMenuCandidates({pageSize:20,...menuCandidateDateParams(menuSearchStart,menuSearchEnd),enabled:!menuSearchError})
  const menuIds=[...selectedMenuMap.keys()]
  const [rangeMode,setRangeMode]=useState<RangeMode>('all')
  const [startDate,setStartDate]=useState(''); const [endDate,setEndDate]=useState('')
  const [result,setResult]=useState<Result|null>(null); const [view,setView]=useState<'daily'|'supplier'|'total'>('daily')
  const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  const [snapshotMessage,setSnapshotMessage]=useState(''); const [savingSnapshot,setSavingSnapshot]=useState(false)
  const [copyMessage,setCopyMessage]=useState('')
  const [supplierKey,setSupplierKey]=useState('')
  const selectedMenus=[...selectedMenuMap.values()]
  const rangeMin=selectedMenus.length?selectedMenus.reduce((value,menu)=>menu.start_date<value?menu.start_date:value,selectedMenus[0].start_date):''
  const rangeMax=selectedMenus.length?selectedMenus.reduce((value,menu)=>menu.end_date>value?menu.end_date:value,selectedMenus[0].end_date):''
  const rangeError=rangeMode==='custom'&&(!startDate||!endDate)?'請同時選擇開始日期與結束日期。':rangeMode==='custom'&&startDate>endDate?'開始日期不可晚於結束日期。':rangeMode==='custom'&&rangeMin&&(startDate<rangeMin||endDate>rangeMax)?'日期必須落在已選菜單的可用範圍內。':''
  const criteriaDates=rangeMode==='custom'?{start_date:startDate,end_date:endDate}:{start_date:null,end_date:null}
  function toggle(menu:Menu){setSelectedMenuMap(current=>{const next=new Map(current);if(next.has(menu.id))next.delete(menu.id);else next.set(menu.id,menu);return next})}
  function changeRangeMode(mode:RangeMode){setRangeMode(mode);if(mode==='all'){setStartDate('');setEndDate('')}else{setStartDate(rangeMin);setEndDate(rangeMax)}}
  async function calculate(event:FormEvent){event.preventDefault();if(!menuIds.length){setError('請至少選擇一份菜單');return}if(rangeError)return;setLoading(true);setError('');try{const data=await apiRequest<Result>('/requirements/calculate',{method:'POST',body:JSON.stringify({menu_ids:menuIds,...criteriaDates})});setResult(data);setSupplierKey(supplierOptions(data.daily_rows)[0]?.key??'');setView('daily')}catch{setError('需求量計算失敗，請檢查日期範圍與菜單資料')}finally{setLoading(false)}}
  async function saveSnapshot(){if(rangeError)return;setSavingSnapshot(true);setSnapshotMessage('');try{await apiRequest('/requirement-snapshots',{method:'POST',body:JSON.stringify({criteria:{menu_ids:menuIds,...criteriaDates}})});setSnapshotMessage('固定需求快照已建立')}catch(error){setSnapshotMessage(error instanceof Error&&error.message.includes('409')?'相同條件的固定快照已存在':'固定快照建立失敗')}finally{setSavingSnapshot(false)}}
  async function download(){if(rangeError)return;setLoading(true);setError('');try{await apiDownload('/exports/requirements/xlsx',{method:'POST',body:JSON.stringify({menu_ids:menuIds,...criteriaDates})})}catch{setError('需求量 Excel 下載失敗')}finally{setLoading(false)}}
  function showCopyMessage(value:string){setCopyMessage(value);window.setTimeout(()=>setCopyMessage(current=>current===value?'':current),2500)}
  async function copyCurrent(){if(!result)return;const text=view==='total'?buildTsv(['食材編號','食材','供應商','需求量','單位','建議採購量','採購單位','現價','預估成本','狀態'],result.rows.map(row=>[row.ingredient_code,row.ingredient_name,row.supplier_name??'未指定供應商',plainDecimal(row.requirement_quantity),row.requirement_unit,row.suggested_purchase_quantity===null?'':plainDecimal(row.suggested_purchase_quantity),row.suggested_purchase_unit??'',row.current_price===null?'':plainDecimal(row.current_price),row.estimated_cost===null?'':plainDecimal(row.estimated_cost),row.needs_review?'需確認':'正常'])):view==='supplier'?supplierRowsTsv(result.daily_rows,supplierKey):dailyRowsTsv(result.daily_rows,'daily');try{await writeClipboard(text);showCopyMessage('已複製，可直接貼到 Excel')}catch{showCopyMessage('複製失敗，請重新操作')}}
  const anomalyGroups=groupAnomalies(result?.anomalies??[])
  const issueKinds=anomalyGroups.filter(group=>group.severity==='error').length
  const affectedOccurrences=anomalyGroups.filter(group=>group.severity==='error').reduce((total,group)=>total+group.count,0)
  const reminderKinds=anomalyGroups.filter(group=>group.severity==='warning').length
  return <section><div className="section-heading"><div><h2>需求量預覽</h2><small>此頁只讀取並計算現有菜單，不會建立需求單或修改資料。</small></div></div>
    <form className="calculation-workflow" onSubmit={calculate}><fieldset className="workflow-step"><legend>① 搜尋並選擇菜單</legend><strong>已選 {menuIds.length} 份菜單</strong><div><strong>搜尋菜單日期</strong><small>只顯示與此期間有交集的菜單；日期留空時顯示一般候選菜單。</small><div className="date-range-fields"><label>搜尋開始日期<input type="date" value={menuSearchStart} onChange={event=>setMenuSearchStart(event.target.value)}/></label><label>搜尋結束日期<input type="date" value={menuSearchEnd} onChange={event=>setMenuSearchEnd(event.target.value)}/></label></div>{menuSearchError&&<p className="error inline-validation">{menuSearchError}</p>}</div><label>菜單關鍵字<input value={menuCandidates.search} onChange={event=>menuCandidates.setSearch(event.target.value)}/></label>{menuCandidates.error&&<small className="error">{menuCandidates.error}</small>}<div className="menu-choices">{preserveSelected(menuCandidates.items,selectedMenuMap).map(menu=><label className="inline-check" key={menu.id}><input type="checkbox" checked={menuIds.includes(menu.id)} onChange={()=>toggle(menu)}/><span>{menu.name}（{menu.start_date}～{menu.end_date}）{!menu.is_active?'〔停用〕':''}</span></label>)}</div>{menuCandidates.loading&&<small>菜單候選載入中…</small>}<PaginationControls page={menuCandidates.page} pageSize={menuCandidates.pageSize} total={menuCandidates.total} onPage={menuCandidates.setPage}/></fieldset><fieldset className="workflow-step"><legend>② 計算日期</legend><small>決定實際需求量計算期間。</small><div className="range-options"><label className="inline-check"><input type="radio" checked={rangeMode==='all'} onChange={()=>changeRangeMode('all')}/>全部已選菜單日期</label><label className="inline-check"><input type="radio" checked={rangeMode==='custom'} disabled={!menuIds.length} onChange={()=>changeRangeMode('custom')}/>自訂日期範圍</label></div>{rangeMode==='custom'&&<div className="date-range-fields"><label>計算開始日期<input type="date" min={rangeMin} max={rangeMax} value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>計算結束日期<input type="date" min={rangeMin} max={rangeMax} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>}{rangeError&&<p className="error inline-validation">{rangeError}</p>}</fieldset><div className="workflow-submit"><strong>③ 計算</strong><button disabled={loading||Boolean(rangeError)}>{loading?'計算中…':'計算需求量'}</button></div></form>
    {error&&<p className="error">{error}</p>}{result&&<><div className="requirement-summary summary-cards"><div><small>預估成本</small><strong>{formatMoney(result.total_estimated_cost??result.known_estimated_cost)}</strong><span>{result.total_estimated_cost===null?'部分食材缺少價格，總成本尚未完整':'成本資料完整'}</span></div><div><small>資料問題</small><strong>{issueKinds} 個</strong><span>影響 {affectedOccurrences} 筆菜單內容</span></div><div><small>提醒</small><strong>{reminderKinds} 項</strong><span>請依下方分組確認</span></div></div>
      <div className="snapshot-action"><button type="button" className="secondary" disabled={loading} onClick={()=>void download()}>下載 Excel</button><button type="button" disabled={savingSnapshot} onClick={()=>void saveSnapshot()}>{savingSnapshot?'儲存中…':'儲存為固定需求快照'}</button><small>快照建立後不受菜單、配方、食材或價格後續修改影響。</small>{snapshotMessage&&<strong>{snapshotMessage}</strong>}</div>
      <AnomalyGroups groups={anomalyGroups}/>
      <div className="requirement-view-toolbar"><div className="requirement-view-tabs" role="tablist" aria-label="需求量檢視"><button type="button" className={view==='daily'?'':'secondary'} onClick={()=>{setView('daily');setCopyMessage('')}}>每日需求</button><button type="button" className={view==='supplier'?'':'secondary'} onClick={()=>{setView('supplier');setCopyMessage('')}}>單一供應商</button><button type="button" className={view==='total'?'':'secondary'} onClick={()=>{setView('total');setCopyMessage('')}}>總需求</button></div>{view==='supplier'&&<label className="supplier-selector">供應商<select value={supplierKey} onChange={event=>{setSupplierKey(event.target.value);setCopyMessage('')}}>{supplierOptions(result.daily_rows).map(option=><option key={option.key} value={option.key}>{option.label}</option>)}</select></label>}<button type="button" disabled={view==='supplier'&&!supplierKey} onClick={()=>void copyCurrent()}>{view==='supplier'?'複製此供應商':'複製目前表格'}</button>{copyMessage&&<small className={copyMessage.startsWith('已複製')?'success':'error'}>{copyMessage}</small>}</div>
      {view==='daily'&&<DailyRequirementTable rows={sortDailyRows(result.daily_rows,'daily')} showSupplier/>} {view==='supplier'&&<DailyRequirementTable rows={filterSupplierRows(result.daily_rows,supplierKey)} showSupplier={false}/>} {view==='total'&&<RequirementTable rows={result.rows}/>}</>}
  </section>
}

function DailyRequirementTable({rows,showSupplier}:{rows:DailyRequirementRow[];showSupplier:boolean}){if(!rows.length)return <p>此條件沒有每日需求資料。</p>;return <div className="requirements-table flat-requirements"><table><thead><tr><th>使用日期</th><th>菜單</th>{showSupplier&&<th>供應商</th>}<th>食材編號</th><th>食材</th><th>需求量</th><th>單位</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.requirement_date}-${row.menu_id}-${row.supplier_id??'none'}-${row.ingredient_id}-${row.unit}`}><td>{row.requirement_date}</td><td>{row.menu_name}</td>{showSupplier&&<td>{row.supplier_name??'未指定供應商'}</td>}<td>{row.ingredient_code}</td><td>{row.ingredient_name}</td><td>{formatQuantity(row.quantity)}</td><td>{row.unit}</td></tr>)}</tbody></table></div>}

function RequirementTable({rows}:{rows:Row[]}){return <div className="requirements-table"><table><thead><tr><th>食材</th><th>供應商</th><th>需求量</th><th>建議採購量</th><th>採購設定（參考）</th><th>現價</th><th>預估成本</th><th>狀態</th></tr></thead><tbody>{rows.map(row=><tr key={row.row_key}><td>{row.ingredient_code}　{row.ingredient_name}</td><td>{row.supplier_name??'未指定'}</td><td>{formatQuantity(row.requirement_quantity)} {row.requirement_unit}</td><td>{row.suggested_purchase_quantity===null?'待確認':`${formatQuantity(row.suggested_purchase_quantity)} ${row.suggested_purchase_unit}`}</td><td>{row.configured_purchase_unit??'—'}／包裝 {formatQuantity(row.package_size)}／最低 {formatQuantity(row.minimum_order_quantity)}</td><td>{row.current_price===null?'缺少':formatMoney(row.current_price)}</td><td>{row.estimated_cost===null?'無法估算':formatMoney(row.estimated_cost)}</td><td>{row.needs_review?'需確認':'正常'}</td></tr>)}</tbody></table>{rows.length===0&&<p>此條件沒有可計算的需求資料。</p>}</div>}
