import { FormEvent,useEffect,useState } from 'react'
import { apiRequest } from '../../api/client'
import { Menu } from '../menus/types'
interface Paged<T>{items:T[]}
interface MealType{id:string;name:string;sort_order:number;is_active:boolean}
interface Anomaly{code:string;severity:'warning'|'error';message:string}
interface Ingredient{ingredient_id:string|null;ingredient_code:string|null;ingredient_name:string|null;supplier_name:string|null;quantity_per_person:string|null;recipe_unit:string|null;loss_rate:string|null;required_quantity:string|null;required_unit:string|null;display_quantity:string|null;display_unit:string|null;notes:string|null;sort_order:number|null;anomalies:Anomaly[]}
interface Dish{dish_id:string;dish_code:string;dish_name:string;diner_count:number;notes:string|null;sort_order:number;recipe_ready:boolean;ingredients:Ingredient[];anomalies:Anomaly[]}
interface Meal{meal_type_id:string;meal_type_name:string;dishes:Dish[];anomalies:Anomaly[]}
interface Day{menu_date:string;meals:Meal[];anomalies:Anomaly[]}
interface Summary{row_key:string;ingredient_code:string;ingredient_name:string;supplier_name:string|null;required_quantity:string;required_unit:string;display_quantity:string;display_unit:string;source_count:number;anomalies:Anomaly[]}
interface SupplierGroup{supplier_id:string|null;supplier_name:string;ingredients:Summary[]}
interface Result{menu:{menu_name:string};days:Day[];ingredient_summary:Summary[];supplier_summary:SupplierGroup[];anomalies:Anomaly[];anomaly_summary:{errors:number;warnings:number}}

export function KitchenOperationsPage(){
  const [menus,setMenus]=useState<Menu[]>([]);const [menuId,setMenuId]=useState('');const [mealTypes,setMealTypes]=useState<MealType[]>([]);const [mealIds,setMealIds]=useState<string[]>([]);const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');const [displayMode,setDisplayMode]=useState<'auto'|'raw'>('auto');const [view,setView]=useState<'dish'|'ingredient'|'supplier'>('dish');const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{void apiRequest<Paged<Menu>>('/menus?page=1&page_size=100').then(data=>setMenus(data.items)).catch(()=>setError('菜單載入失敗'))},[])
  useEffect(()=>{setMealIds([]);if(!menuId){setMealTypes([]);return}void apiRequest<MealType[]>(`/menus/${menuId}/meal-types`).then(setMealTypes).catch(()=>setError('餐別載入失敗'))},[menuId])
  function toggleMeal(id:string){setMealIds(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id])}
  async function calculate(event:FormEvent){event.preventDefault();if(!menuId){setError('請選擇菜單');return}if(Boolean(startDate)!==Boolean(endDate)){setError('開始與結束日期需同時填寫；單日請填相同日期');return}setLoading(true);setError('');try{setResult(await apiRequest<Result>('/kitchen-operations/calculate',{method:'POST',body:JSON.stringify({menu_id:menuId,start_date:startDate||null,end_date:endDate||null,meal_type_ids:mealIds.length?mealIds:null,display_mode:displayMode})}))}catch{setError('廚房作業查詢失敗，請檢查菜單與日期條件')}finally{setLoading(false)}}
  return <section><div className="section-heading"><div><h2>廚房作業</h2><small>依菜單、日期、餐別及菜色顯示備料量；不使用快照、人工採購量或正式採購資料。</small></div></div>
    <form className="kitchen-filter" onSubmit={calculate}><label>菜單<select value={menuId} onChange={e=>setMenuId(e.target.value)} required><option value="">請選擇</option>{menus.map(menu=><option key={menu.id} value={menu.id}>{menu.name}（{menu.start_date}～{menu.end_date}）</option>)}</select></label><label>開始日期<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>結束日期<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>顯示單位<select value={displayMode} onChange={e=>setDisplayMode(e.target.value as 'auto'|'raw')}><option value="auto">自動易讀</option><option value="raw">配方原始單位</option></select></label><fieldset><legend>餐別（未選表示全部）</legend>{mealTypes.map(meal=><label className="inline-check" key={meal.id}><input type="checkbox" checked={mealIds.includes(meal.id)} onChange={()=>toggleMeal(meal.id)}/>{meal.name}{!meal.is_active?'〔停用〕':''}</label>)}</fieldset><button disabled={loading}>{loading?'計算中…':'查看備料'}</button></form>
    {error&&<p className="error">{error}</p>}{result&&<><div className="requirement-summary"><strong>{result.menu.menu_name}</strong><span>{result.anomaly_summary.errors} 錯誤／{result.anomaly_summary.warnings} 警告</span><div className="actions"><button className={view==='dish'?'':'secondary'} onClick={()=>setView('dish')}>依菜色</button><button className={view==='ingredient'?'':'secondary'} onClick={()=>setView('ingredient')}>食材總量</button><button className={view==='supplier'?'':'secondary'} onClick={()=>setView('supplier')}>依供應商</button></div></div>{result.anomalies.length>0&&<div className="anomaly-list"><h3>備料提醒</h3><ul>{result.anomalies.map((a,index)=><li className={a.severity} key={`${a.code}-${index}`}><strong>{a.code}</strong>：{a.message}</li>)}</ul></div>}
      {view==='dish'&&result.days.map(day=><section className="kitchen-day" key={day.menu_date}><h3>{day.menu_date}</h3>{day.meals.map(meal=><div className="kitchen-meal" key={meal.meal_type_id}><h3>{meal.meal_type_name}</h3>{meal.dishes.map(dish=><article className={`kitchen-dish ${dish.recipe_ready?'':'not-ready'}`} key={`${meal.meal_type_id}-${dish.dish_id}`}><div className="section-heading"><h4>{dish.dish_code}　{dish.dish_name}</h4><strong>{dish.diner_count} 人／順序 {dish.sort_order}</strong></div>{dish.notes&&<p>餐格備註：{dish.notes}</p>}{dish.ingredients.length?<table><thead><tr><th>順序</th><th>食材</th><th>每人量</th><th>耗損率</th><th>備料量</th><th>配方備註</th><th>狀態</th></tr></thead><tbody>{dish.ingredients.map((line,index)=><tr key={line.ingredient_id??index}><td>{line.sort_order??'—'}</td><td>{line.ingredient_code}　{line.ingredient_name}</td><td>{line.quantity_per_person??'—'} {line.recipe_unit}</td><td>{line.loss_rate??'—'}%</td><td>{line.display_quantity===null?'不可計算':`${line.display_quantity} ${line.display_unit}`}</td><td>{line.notes??'—'}</td><td>{line.anomalies.map(a=>a.code).join('、')||'正常'}</td></tr>)}</tbody></table>:<p className="error">尚無可用配方</p>}</article>)}</div>)}</section>)}
      {view==='ingredient'&&<SummaryTable items={result.ingredient_summary}/>} {view==='supplier'&&result.supplier_summary.map(group=><section key={group.supplier_id??'none'}><h3>{group.supplier_name}</h3><SummaryTable items={group.ingredients}/></section>)}</>}
  </section>
}
function SummaryTable({items}:{items:Summary[]}){return <div className="requirements-table"><table><thead><tr><th>食材</th><th>供應商</th><th>總備料量</th><th>來源數</th><th>狀態</th></tr></thead><tbody>{items.map(item=><tr key={item.row_key}><td>{item.ingredient_code}　{item.ingredient_name}</td><td>{item.supplier_name??'未指定'}</td><td>{item.display_quantity} {item.display_unit}</td><td>{item.source_count}</td><td>{item.anomalies.map(a=>a.code).join('、')||'正常'}</td></tr>)}</tbody></table></div>}
