import { FormEvent, useCallback, useEffect, useState } from 'react'
import { apiRequest } from '../../api/client'

interface Option { id: string; name: string; is_active: boolean }
interface Supplier { id: string; name: string; is_active: boolean }
interface Ingredient { id: string; code: string; name: string; category_name: string; supplier_name: string | null; unit: string; current_price: string; is_active: boolean }
interface List<T> { items: T[] }

export function IngredientsPage() {
  const [items, setItems] = useState<Ingredient[]>([]); const [categories, setCategories] = useState<Option[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [code, setCode] = useState(''); const [name, setName] = useState(''); const [categoryId, setCategoryId] = useState(''); const [supplierId, setSupplierId] = useState(''); const [unit, setUnit] = useState('kg'); const [price, setPrice] = useState('0'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [ingredients, categoryList, supplierList] = await Promise.all([apiRequest<List<Ingredient>>('/ingredients'), apiRequest<List<Option>>('/categories/ingredient?active=true&page_size=100'), apiRequest<List<Supplier>>('/suppliers?active=true&page_size=100')]); setItems(ingredients.items); setCategories(categoryList.items); setSuppliers(supplierList.items); setCategoryId(current => current || categoryList.items[0]?.id || ''); setError('') } catch { setError('食材資料載入失敗') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  async function create(event: FormEvent) { event.preventDefault(); try { await apiRequest('/ingredients', { method: 'POST', body: JSON.stringify({ code, name, category_id: categoryId, primary_supplier_id: supplierId || null, unit, current_price: price, purchase_unit: unit, package_size: '1', minimum_order_quantity: '0' }) }); setCode(''); setName(''); setPrice('0'); await load() } catch { setError('食材新增失敗，請檢查代碼、分類與數值') } }
  async function edit(item: Ingredient) { const nextName = window.prompt('食材名稱', item.name); if (!nextName) return; const nextPrice = window.prompt('目前單價', item.current_price); if (nextPrice === null) return; try { await apiRequest(`/ingredients/${item.id}`, { method: 'PATCH', body: JSON.stringify({ name: nextName, current_price: nextPrice }) }); await load() } catch { setError('食材修改失敗') } }
  async function toggle(item: Ingredient) { await apiRequest(`/ingredients/${item.id}/${item.is_active ? 'deactivate' : 'reactivate'}`, { method: 'POST' }); await load() }
  async function history(item: Ingredient) { try { const rows = await apiRequest<Array<{ effective_date: string; price: string; unit: string }>>(`/ingredients/${item.id}/price-history`); window.alert(rows.map(row => `${row.effective_date}｜${row.price} ${row.unit}`).join('\n') || '沒有價格歷史') } catch { setError('價格歷史載入失敗') } }
  async function hardDelete(item: Ingredient) { if (!window.confirm('永久刪除後無法復原；有價格或業務歷史時將拒絕')) return; const password = window.prompt('請重新輸入目前帳號密碼'); if (!password) return; try { await apiRequest(`/ingredients/${item.id}/hard-delete`, { method: 'POST', body: JSON.stringify({ password }) }); await load() } catch { setError('食材已有價格或業務歷史，不能永久刪除') } }
  return <section><h2>食材管理</h2><form className="panel-form" onSubmit={create}><label>代碼<input value={code} onChange={e => setCode(e.target.value)} required /></label><label>名稱<input value={name} onChange={e => setName(e.target.value)} required /></label><label>分類<select value={categoryId} onChange={e => setCategoryId(e.target.value)} required><option value="">請選擇</option>{categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>主供應商<select value={supplierId} onChange={e => setSupplierId(e.target.value)}><option value="">無</option>{suppliers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>基本單位<input value={unit} onChange={e => setUnit(e.target.value)} required /></label><label>目前單價<input type="number" min="0" step="0.0001" value={price} onChange={e => setPrice(e.target.value)} required /></label><button>新增食材</button></form>{error && <p className="error">{error}</p>}{loading ? <p>載入中…</p> : <table><thead><tr><th>代碼</th><th>名稱</th><th>分類</th><th>供應商</th><th>單價</th><th>狀態</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.category_name}</td><td>{item.supplier_name ?? '—'}</td><td>{item.current_price} / {item.unit}</td><td>{item.is_active ? '啟用' : '停用'}</td><td className="actions"><button onClick={() => void edit(item)}>修改</button><button onClick={() => void history(item)}>價格歷史</button><button onClick={() => void toggle(item)}>{item.is_active ? '停用' : '恢復'}</button><button className="danger" onClick={() => void hardDelete(item)}>永久刪除</button></td></tr>)}</tbody></table>}</section>
}
