import { FormEvent,useCallback,useEffect,useRef,useState } from 'react'
import { ApiError,apiRequest } from '../../api/client'
import { EmptyState,Feedback,LoadingState,TableFrame } from '../../components/ui/Page'
import { PaginationControls } from '../../components/ui/PaginationControls'
import { buildListQuery,PagedResponse,RequestSequence } from '../../utils/listQuery'
import { formatNutritionValue } from '../../utils/numbers'
import { useDebouncedValue } from '../../utils/useDebouncedValue'
import { activeCategoryOptions,editableCategoryOptions,IngredientCategoryOption,IngredientSupplierOption,loadIngredientCandidates } from './ingredientCandidates'

type Option=IngredientCategoryOption
type Supplier=IngredientSupplierOption
interface Ingredient{id:string;code:string;name:string;category_id:string;category_name:string;primary_supplier_id:string|null;supplier_name:string|null;unit:string;current_price:string;is_active:boolean;nutrition_food_id:string|null;nutrition_status:'official'|'manual'|'none';nutrition_food_name:string|null;nutrition_external_code:string|null;nutrition_corrected_energy:string|null}
interface NutritionFood{id:string;source:'tfda'|'manual';external_code:string|null;name:string;category:string|null;brand:string|null;corrected_energy:string|null}
interface List<T>{items:T[]}
const units=['g','kg','斤','片','個','隻','盒','箱','ml','L','罐','桶'] as const

function ingredientError(error:unknown,fallback:string){
  if(error instanceof ApiError&&error.status===409){const message=error.message.toLowerCase();if(message.includes('code'))return '食材代碼已存在，請使用其他代碼。';if(message.includes('名稱')||message.includes('name'))return '食材名稱已存在，請使用其他名稱。';return '食材仍有價格或業務歷史，無法永久刪除。'}
  if(error instanceof ApiError&&error.status===401)return '目前密碼不正確，請重新輸入。'
  if(error instanceof ApiError&&error.status===422)return '請檢查必填欄位、單位與數值格式。'
  return fallback
}

function UnitSelect({value,onChange}:{value:string;onChange:(value:string)=>void}){
  const isListed=units.includes(value as (typeof units)[number])
  return <select value={value} onChange={event=>onChange(event.target.value)} required>{!isListed&&<option value={value} disabled>{value}（目前值，請改選）</option>}{units.map(unit=><option key={unit} value={unit}>{unit}</option>)}</select>
}

function IngredientEditDialog({ingredient,categories,suppliers,busy,error,onClose,onSave,onNutrition,onClearNutrition}:{ingredient:Ingredient;categories:Option[];suppliers:Supplier[];busy:boolean;error:string;onClose:()=>void;onSave:(values:{code:string;name:string;category_id:string;primary_supplier_id:string|null;unit:string;current_price:string})=>Promise<void>;onNutrition:()=>void;onClearNutrition:()=>void}){
  const [code,setCode]=useState(ingredient.code),[name,setName]=useState(ingredient.name),[categoryId,setCategoryId]=useState(ingredient.category_id),[supplierId,setSupplierId]=useState(ingredient.primary_supplier_id??''),[unit,setUnit]=useState(ingredient.unit),[price,setPrice]=useState(ingredient.current_price)
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[busy,onClose])
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="modal-panel ingredient-dialog" role="dialog" aria-modal="true" aria-labelledby="ingredient-edit-title"><header><div><h2 id="ingredient-edit-title">編輯食材</h2><p>更新食材主檔；營養對應是獨立設定，不會改動食材名稱、價格或單位。</p></div></header><form onSubmit={event=>{event.preventDefault();void onSave({code:code.trim(),name:name.trim(),category_id:categoryId,primary_supplier_id:supplierId||null,unit,current_price:price})}}><div className="ingredient-edit-fields"><label>代碼<input autoFocus required maxLength={50} value={code} onChange={event=>setCode(event.target.value)}/></label><label>名稱<input required maxLength={150} value={name} onChange={event=>setName(event.target.value)}/></label><label>分類<select required value={categoryId} onChange={event=>setCategoryId(event.target.value)}>{editableCategoryOptions(categories,ingredient.category_id).map(item=><option key={item.id} value={item.id}>{item.name}{item.is_active?'':'（已停用）'}</option>)}</select></label><label>主要供應商<select value={supplierId} onChange={event=>setSupplierId(event.target.value)}><option value="">無</option>{suppliers.map(item=><option key={item.id} value={item.id} disabled={!item.is_active&&item.id!==ingredient.primary_supplier_id}>{item.name}{item.is_active?'':'（已停用）'}</option>)}</select></label><label>基本單位<UnitSelect value={unit} onChange={setUnit}/></label><label>目前單價<input type="number" min="0" step="0.0001" required value={price} onChange={event=>setPrice(event.target.value)}/></label></div><section className="nutrition-mapping-summary"><strong>營養資料來源：{ingredient.nutrition_status==='official'?'台灣食品營養成分資料庫':ingredient.nutrition_status==='manual'?'手動營養食品':'未設定'}</strong>{ingredient.nutrition_food_name&&<p>目前對應：{ingredient.nutrition_food_name}　{ingredient.nutrition_external_code??''}　修正熱量 {formatNutritionValue(ingredient.nutrition_corrected_energy)} kcal／100 g</p>}<div className="actions"><button type="button" className="secondary" onClick={onNutrition}>變更</button>{ingredient.nutrition_food_id&&<button type="button" className="secondary" onClick={onClearNutrition}>清除對應</button>}</div></section>{error&&<Feedback type="error">{error}</Feedback>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button disabled={busy||!code.trim()||!name.trim()||!categoryId}>{busy?'儲存中…':'儲存'}</button></footer></form></section></div>
}

function NutritionMappingDialog({ingredient,busy,error,onClose,onSave}:{ingredient:Ingredient;busy:boolean;error:string;onClose:()=>void;onSave:(id:string|null)=>void}){
  const [source,setSource]=useState<'official'|'manual'|'none'>(ingredient.nutrition_status),[search,setSearch]=useState(''),[items,setItems]=useState<NutritionFood[]>([]),[selected,setSelected]=useState(ingredient.nutrition_food_id??''),[loading,setLoading]=useState(false);const debounced=useDebouncedValue(search)
  useEffect(()=>{if(source==='none'){setItems([]);setSelected('');return}setLoading(true);const query=new URLSearchParams({source:source==='official'?'tfda':'manual',active:'true',page_size:'10'});if(debounced)query.set('search',debounced);void apiRequest<PagedResponse<NutritionFood>>(`/nutrition/foods?${query}`).then(result=>setItems(result.items)).catch(()=>setItems([])).finally(()=>setLoading(false))},[debounced,source])
  const chosen=items.find(item=>item.id===selected)
  return <div className="modal-backdrop"><section className="modal-panel" role="dialog" aria-modal="true"><header><div><h2>設定「{ingredient.name}」營養資料</h2><p>只變更營養對應，不會修改 KitchenERP 食材主檔。</p></div></header><fieldset className="nutrition-source-options"><legend>營養資料來源</legend><label><input type="radio" checked={source==='official'} onChange={()=>{setSource('official');setSelected('')}}/>台灣食品營養成分資料庫</label><label><input type="radio" checked={source==='manual'} onChange={()=>{setSource('manual');setSelected('')}}/>手動營養食品</label><label><input type="radio" checked={source==='none'} onChange={()=>setSource('none')}/>未設定</label></fieldset>{source!=='none'&&<><label>搜尋<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="整合編號、樣品名稱、分類或俗名"/></label><div className="nutrition-picker-results">{loading?<small>搜尋中…</small>:items.map(item=><label key={item.id}><input type="radio" name="nutrition-food" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span><strong>{item.name}</strong><small>{item.external_code??item.brand??'手動'}｜{item.category??'未分類'}｜修正熱量 {formatNutritionValue(item.corrected_energy)} kcal／100 g</small></span></label>)}</div>{chosen&&<div className="nutrition-selected"><strong>已選：{chosen.name}</strong><span>整合編號：{chosen.external_code??'—'}</span><span>分類：{chosen.category??'—'}</span><span>修正熱量：{formatNutritionValue(chosen.corrected_energy)} kcal／100 g</span></div>}</>}{error&&<Feedback type="error">{error}</Feedback>}<footer><button className="secondary" disabled={busy} onClick={onClose}>取消</button><button disabled={busy||(source!=='none'&&!selected)} onClick={()=>onSave(source==='none'?null:selected)}>{busy?'儲存中…':'保存對應'}</button></footer></section></div>
}

function IngredientDeleteDialog({ingredient,busy,error,onClose,onDelete}:{ingredient:Ingredient;busy:boolean;error:string;onClose:()=>void;onDelete:(password:string)=>Promise<void>}){
  const [password,setPassword]=useState('')
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[busy,onClose])
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="modal-panel ingredient-dialog" role="dialog" aria-modal="true" aria-labelledby="ingredient-delete-title"><header><div><h2 id="ingredient-delete-title">永久刪除「{ingredient.name}」</h2><p>此操作無法復原。有價格或業務歷史時，系統會拒絕刪除。</p></div></header><form onSubmit={event=>{event.preventDefault();void onDelete(password)}}><label>目前密碼<input autoFocus required type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label>{error&&<Feedback type="error">{error}</Feedback>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button className="danger" disabled={busy||!password}>{busy?'刪除中…':'永久刪除'}</button></footer></form></section></div>
}

export function IngredientsPage(){
  const [items,setItems]=useState<Ingredient[]>([]),[categories,setCategories]=useState<Option[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([])
  const [code,setCode]=useState(''),[name,setName]=useState(''),[categoryId,setCategoryId]=useState(''),[supplierId,setSupplierId]=useState(''),[unit,setUnit]=useState('kg'),[price,setPrice]=useState('0'),[error,setError]=useState(''),[categoryOptionsError,setCategoryOptionsError]=useState(''),[supplierOptionsError,setSupplierOptionsError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
  const [editing,setEditing]=useState<Ingredient|null>(null),[mapping,setMapping]=useState<Ingredient|null>(null),[deleting,setDeleting]=useState<Ingredient|null>(null),[dialogError,setDialogError]=useState('')
  const [search,setSearch]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[activeFilter,setActiveFilter]=useState(''),[nutritionFilter,setNutritionFilter]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[total,setTotal]=useState(0)
  const debouncedSearch=useDebouncedValue(search),sequence=useRef(new RequestSequence())
  const load=useCallback(async()=>{const request=sequence.current.next();setLoading(true);try{const query=buildListQuery({page,pageSize,search:debouncedSearch,active:activeFilter,categoryId:categoryFilter})+(nutritionFilter?`&nutrition_status=${nutritionFilter}`:'');const ingredients=await apiRequest<PagedResponse<Ingredient>>(`/ingredients?${query}`);if(sequence.current.isCurrent(request)){setItems(ingredients.items);setTotal(ingredients.pagination.total);setError('')}}catch{if(sequence.current.isCurrent(request))setError('食材資料載入失敗')}finally{if(sequence.current.isCurrent(request))setLoading(false)}},[activeFilter,categoryFilter,debouncedSearch,nutritionFilter,page,pageSize])
  useEffect(()=>{let current=true;void loadIngredientCandidates(()=>apiRequest<List<Option>>('/categories/ingredient?page_size=100'),()=>apiRequest<List<Supplier>>('/suppliers?page_size=100')).then(result=>{if(!current)return;if(result.categories){setCategories(result.categories);setCategoryId(selected=>selected||result.categories?.find(item=>item.is_active)?.id||'')}if(result.suppliers)setSuppliers(result.suppliers);setCategoryOptionsError(result.categoryFailed?'分類載入失敗，請稍後再試。':'');setSupplierOptionsError(result.supplierFailed?'供應商載入失敗，請稍後再試。':'')});return()=>{current=false}},[])
  useEffect(()=>{void load()},[load])
  async function create(event:FormEvent){event.preventDefault();try{const created=await apiRequest<Ingredient>('/ingredients',{method:'POST',body:JSON.stringify({code,name,category_id:categoryId,primary_supplier_id:supplierId||null,unit,current_price:price,purchase_unit:unit,package_size:'1',minimum_order_quantity:'0'})});setCode('');setName('');setPrice('0');await load();setMapping(created)}catch(cause){setError(ingredientError(cause,'食材新增失敗，請檢查代碼、分類與數值。'))}}
  async function saveEdit(values:{code:string;name:string;category_id:string;primary_supplier_id:string|null;unit:string;current_price:string}){if(!editing)return;setBusy(true);setDialogError('');try{await apiRequest(`/ingredients/${editing.id}`,{method:'PATCH',body:JSON.stringify(values)});setEditing(null);await load()}catch(cause){setDialogError(ingredientError(cause,'食材修改失敗，請稍後重試。'))}finally{setBusy(false)}}
  async function toggle(item:Ingredient){await apiRequest(`/ingredients/${item.id}/${item.is_active?'deactivate':'reactivate'}`,{method:'POST'});await load()}
  async function history(item:Ingredient){try{const rows=await apiRequest<Array<{effective_date:string;price:string;unit:string}>>(`/ingredients/${item.id}/price-history`);window.alert(rows.map(row=>`${row.effective_date}｜${row.price} ${row.unit}`).join('\n')||'沒有價格歷史')}catch{setError('價格歷史載入失敗')}}
  async function hardDelete(password:string){if(!deleting)return;setBusy(true);setDialogError('');try{await apiRequest(`/ingredients/${deleting.id}/hard-delete`,{method:'POST',body:JSON.stringify({password})});setDeleting(null);await load()}catch(cause){setDialogError(ingredientError(cause,'食材無法永久刪除，請稍後重試。'))}finally{setBusy(false)}}
  async function saveMapping(foodId:string|null){if(!mapping)return;setBusy(true);setDialogError('');try{await apiRequest(`/ingredients/${mapping.id}/nutrition`,{method:'PATCH',body:JSON.stringify({nutrition_food_id:foodId})});setMapping(null);setEditing(null);await load()}catch(cause){setDialogError(ingredientError(cause,'營養對應儲存失敗，請稍後重試。'))}finally{setBusy(false)}}
  async function clearMapping(ingredient:Ingredient){setBusy(true);setDialogError('');try{await apiRequest(`/ingredients/${ingredient.id}/nutrition`,{method:'PATCH',body:JSON.stringify({nutrition_food_id:null})});setEditing(null);await load()}catch(cause){setDialogError(ingredientError(cause,'清除營養對應失敗，請稍後重試。'))}finally{setBusy(false)}}
  const resetPage=()=>setPage(1)
  const activeCategories=activeCategoryOptions(categories)
  return <section><h2>食材管理</h2><form className="panel-form" onSubmit={create}><label>代碼<input value={code} onChange={event=>setCode(event.target.value)} required/></label><label>名稱<input value={name} onChange={event=>setName(event.target.value)} required/></label><label>分類<select value={categoryId} onChange={event=>setCategoryId(event.target.value)} required><option value="">請選擇</option>{activeCategories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>主供應商<select value={supplierId} onChange={event=>setSupplierId(event.target.value)}><option value="">無</option>{suppliers.filter(item=>item.is_active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>基本單位<UnitSelect value={unit} onChange={setUnit}/></label><label>目前單價<input type="number" min="0" step="0.0001" value={price} onChange={event=>setPrice(event.target.value)} required/></label><button>新增食材</button></form>
    <div className="toolbar"><label>搜尋<input value={search} onChange={event=>{setSearch(event.target.value);resetPage()}}/></label><label>分類<select value={categoryFilter} onChange={event=>{setCategoryFilter(event.target.value);resetPage()}}><option value="">全部分類</option>{activeCategories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>狀態<select value={activeFilter} onChange={event=>{setActiveFilter(event.target.value);resetPage()}}><option value="">全部</option><option value="true">啟用</option><option value="false">停用</option></select></label><label>營養狀態<select value={nutritionFilter} onChange={event=>{setNutritionFilter(event.target.value);resetPage()}}><option value="">全部</option><option value="official">官方</option><option value="manual">手動</option><option value="none">未設定</option></select></label></div>
    {categoryOptionsError&&<Feedback type="error">{categoryOptionsError}</Feedback>}{supplierOptionsError&&<Feedback type="error">{supplierOptionsError}</Feedback>}{error&&<Feedback type="error">{error}</Feedback>}{loading?<LoadingState/>:!items.length?<EmptyState title="找不到符合條件的食材" description="請調整搜尋或篩選條件。"/>:<TableFrame><table><thead><tr><th>代碼</th><th>名稱</th><th>分類</th><th>供應商</th><th>單價</th><th>營養</th><th>狀態</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.category_name}</td><td>{item.supplier_name??'—'}</td><td>{item.current_price} / {item.unit}</td><td><span className={`status-badge nutrition-${item.nutrition_status}`}>{item.nutrition_status==='official'?'官方':item.nutrition_status==='manual'?'手動':'未設定'}</span></td><td>{item.is_active?'啟用':'停用'}</td><td className="actions"><button onClick={()=>{setDialogError('');setEditing(item)}}>修改</button><button onClick={()=>{setDialogError('');setMapping(item)}}>設定營養資料</button><button onClick={()=>void history(item)}>價格歷史</button><button onClick={()=>void toggle(item)}>{item.is_active?'停用':'恢復'}</button><button className="danger" onClick={()=>{setDialogError('');setDeleting(item)}}>永久刪除</button></td></tr>)}</tbody></table></TableFrame>}<PaginationControls page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={size=>{setPageSize(size);setPage(1)}}/>
    {editing&&<IngredientEditDialog ingredient={editing} categories={categories} suppliers={suppliers} busy={busy} error={dialogError} onClose={()=>setEditing(null)} onSave={saveEdit} onNutrition={()=>{setMapping(editing);setEditing(null)}} onClearNutrition={()=>void clearMapping(editing)}/>} {mapping&&<NutritionMappingDialog ingredient={mapping} busy={busy} error={dialogError} onClose={()=>setMapping(null)} onSave={saveMapping}/>} {deleting&&<IngredientDeleteDialog ingredient={deleting} busy={busy} error={dialogError} onClose={()=>setDeleting(null)} onDelete={hardDelete}/>}</section>
}
