"""add standard recipe cards and production process

Revision ID: 20260901_0012
Revises: 20260901_0011
Create Date: 2026-09-01
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str="20260901_0012";down_revision: str|None="20260901_0011";branch_labels: str|Sequence[str]|None=None;depends_on: str|Sequence[str]|None=None

def audit_columns():return [sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("created_by",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("updated_by",postgresql.UUID(as_uuid=True),nullable=False)]
def actor_fks():return [sa.ForeignKeyConstraint(["created_by"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["updated_by"],["users.id"],ondelete="RESTRICT")]

def upgrade()->None:
    op.create_table("dish_production_profiles",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("dish_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("max_batch_size",sa.Integer(),nullable=False),sa.Column("notes",sa.Text()),sa.Column("image_filename",sa.String(80)),sa.Column("image_mime_type",sa.String(40)),sa.Column("image_size_bytes",sa.Integer()),*audit_columns(),sa.CheckConstraint("max_batch_size > 0",name="ck_dish_production_profiles_max_batch_positive"),sa.ForeignKeyConstraint(["dish_id"],["dishes.id"],ondelete="RESTRICT"),*actor_fks(),sa.PrimaryKeyConstraint("id",name="pk_dish_production_profiles"),sa.UniqueConstraint("dish_id",name="uq_dish_production_profiles_dish_id"));op.create_index("ix_dish_production_profiles_dish_id","dish_production_profiles",["dish_id"])
    op.create_table("production_batch_versions",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("profile_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("serving_count",sa.Integer(),nullable=False),sa.Column("name",sa.String(150)),sa.Column("is_official",sa.Boolean(),server_default="false",nullable=False),sa.Column("notes",sa.Text()),*audit_columns(),sa.CheckConstraint("serving_count > 0",name="ck_production_batch_versions_servings_positive"),sa.ForeignKeyConstraint(["profile_id"],["dish_production_profiles.id"],ondelete="CASCADE"),*actor_fks(),sa.PrimaryKeyConstraint("id",name="pk_production_batch_versions"),sa.UniqueConstraint("profile_id","serving_count",name="uq_production_batch_versions_profile_servings"));op.create_index("ix_production_batch_versions_profile_id","production_batch_versions",["profile_id"])
    op.create_table("production_batch_ingredients",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("version_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("dish_ingredient_id",postgresql.UUID(as_uuid=True)),sa.Column("ingredient_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("quantity",sa.Numeric(24,10),nullable=False),sa.Column("unit",sa.String(30),nullable=False),sa.Column("usage_category",sa.String(32),server_default="main_ingredient",nullable=False),sa.Column("sort_order",sa.Integer(),server_default="0",nullable=False),sa.Column("quantity_note",sa.String(500)),sa.Column("notes",sa.String(1000)),*audit_columns(),sa.CheckConstraint("quantity >= 0",name="ck_production_batch_ingredients_quantity_nonnegative"),sa.CheckConstraint("sort_order >= 0",name="ck_production_batch_ingredients_sort_nonnegative"),sa.CheckConstraint("usage_category IN ('main_ingredient','preprocessing','marinade','seasoning','sauce','final_addition','garnish')",name="ck_production_batch_ingredients_usage"),sa.ForeignKeyConstraint(["version_id"],["production_batch_versions.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["dish_ingredient_id"],["dish_ingredients.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["ingredient_id"],["ingredients.id"],ondelete="RESTRICT"),*actor_fks(),sa.PrimaryKeyConstraint("id",name="pk_production_batch_ingredients"),sa.UniqueConstraint("version_id","ingredient_id",name="uq_production_batch_ingredients_version_ingredient"));op.create_index("ix_production_batch_ingredients_version_id","production_batch_ingredients",["version_id"]);op.create_index("ix_production_batch_ingredients_dish_ingredient_id","production_batch_ingredients",["dish_ingredient_id"]);op.create_index("ix_production_batch_ingredients_ingredient_id","production_batch_ingredients",["ingredient_id"])
    op.create_table("production_process_steps",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("version_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("step_order",sa.Integer(),nullable=False),sa.Column("step_type",sa.String(32),nullable=False),sa.Column("title",sa.String(150)),sa.Column("instruction",sa.Text()),sa.Column("equipment",sa.String(150)),sa.Column("duration_seconds",sa.Integer()),sa.Column("temperature_celsius",sa.Numeric(7,2)),sa.Column("batch_size",sa.Integer()),sa.Column("servings_per_tray",sa.Integer()),sa.Column("trays_per_batch",sa.Integer()),sa.Column("quantity_note",sa.String(500)),sa.Column("notes",sa.String(1000)),*audit_columns(),sa.CheckConstraint("step_order >= 1",name="ck_production_process_steps_order_positive"),sa.CheckConstraint("duration_seconds IS NULL OR duration_seconds >= 0",name="ck_production_process_steps_duration_nonnegative"),sa.CheckConstraint("temperature_celsius IS NULL OR (temperature_celsius >= -100 AND temperature_celsius <= 500)",name="ck_production_process_steps_temperature_range"),sa.CheckConstraint("batch_size IS NULL OR batch_size > 0",name="ck_production_process_steps_batch_positive"),sa.CheckConstraint("servings_per_tray IS NULL OR servings_per_tray > 0",name="ck_production_process_steps_tray_positive"),sa.CheckConstraint("trays_per_batch IS NULL OR trays_per_batch > 0",name="ck_production_process_steps_trays_positive"),sa.CheckConstraint("step_type IN ('wash','cut','chop','marinate','blanch','thaw','stir_fry','boil','braise','steam','bake','fry','pan_fry','add_ingredient','add_water','stir','flip','thicken','sauce','garnish','final_addition','portion','plating','quality_check','other')",name="ck_production_process_steps_type"),sa.ForeignKeyConstraint(["version_id"],["production_batch_versions.id"],ondelete="CASCADE"),*actor_fks(),sa.PrimaryKeyConstraint("id",name="pk_production_process_steps"),sa.UniqueConstraint("version_id","step_order",name="uq_production_process_steps_version_order"));op.create_index("ix_production_process_steps_version_id","production_process_steps",["version_id"])

def downgrade()->None:
    for table in ("production_process_steps","production_batch_ingredients","production_batch_versions","dish_production_profiles"):op.drop_table(table)
